knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/Clinical_Rate_Change__c.object-meta.xml
<CustomObject>
    <label>Clinical Rate Change</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Clinical Rate Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Rate Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <description>stores the Contract Id of user selected Contract.</description>
    <label>Contract ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/Non_Processed_Clinical_Ids__c.field-meta.xml
<CustomField>
    <fullName>Non_Processed_Clinical_Ids__c</fullName>
    <description>In account-management-agent: comma-separated contract IDs selected by user in draft contracts table for post-processing.</description>
    <label>Non Processed Clinical Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/PreviewClonedContractIds__c.field-meta.xml
<CustomField>
    <fullName>PreviewClonedContractIds__c</fullName>
    <description>Used to capture the Clone contracts via preview code(can be max 2 ids based on professional Title).</description>
    <label>PreviewClonedContractIds</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/Service_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_ID__c</fullName>
    <description>stores the Id of user selected Facility</description>
    <label>Service Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/user_selected_IDs__c.field-meta.xml
<CustomField>
    <fullName>user_selected_IDs__c</fullName>
    <description>stores the Ids of Clinicians along with isProcessed attribute in JSON format</description>
    <label>user selected IDs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/RateChangeFinalProcessing.cls
public class RateChangeFinalProcessing {
    @InvocableMethod(
        label='Final Processing' 
        description='Process of final records after displaying message \'Your request has been submitted\' to user'
        category='File Management'
    )
    public static List<FinalOutput> finalProcessRateChange(List<FinalInput> requests) {
        List<FinalOutput> lstFinalOut = new List<FinalOutput>();
        List<Clinical_Rate_Change__c> lstAgData = new List<Clinical_Rate_Change__c>();
        List<Id> returnedContractIds = new List<Id>();
        List<String> allSelectedIdsListString;
        list<string> PreviewClonedContractIds = new list<string>();
        
        FinalInput request = requests[0];
        
        lstAgData = [SELECT id,
                     user_selected_IDs__c,
                     Service_Account_ID__c ,
                     PreviewClonedContractIds__c,
                     Non_Processed_Clinical_Ids__c,
                     Contract_ID__c,
                     CreatedById
                     FROM Clinical_Rate_Change__c 
                     WHERE  Service_Account_ID__c= :request.accountId and Contract_ID__c = :request.contractId and Status__c = 'Open'];
        
        if(lstAgData!=NULL && lstAgData.size()>0){
            if(lstAgData[0].Non_Processed_Clinical_Ids__c !=NULL && String.ISNOTBlank(lstAgData[0].Non_Processed_Clinical_Ids__c)){
            Object jsonResult = JSON.deserializeUntyped(lstAgData[0].Non_Processed_Clinical_Ids__c);
            allSelectedIdsListString =  fileToLinkGenerator.extractSelectedClinicianIds(jsonResult);
            }
        }
        
        //converting List<String> allSelectedIdsListString to List<Id> allSelectedIdsList
        List<Id> allSelectedIdsList = new List<Id>();
        String userSelectedContractId;
        if(allSelectedIdsListString!=null && allSelectedIdsListString.size()>0){
            for (String idStr : allSelectedIdsListString) {
                    if (String.isNotBlank(idStr)) {
                        allSelectedIdsList.add((Id)idStr);
                    }
            }
        }
		 
        if(!lstAgData.isEmpty())
        userSelectedContractId = lstAgData[0].Contract_ID__c; 
        
        // if userConsent is True 
        if(request.userConsent ){   
            RateChangeService rcsObj = new RateChangeService();
            
            if(lstAgData.size()>0){
                returnedContractIds  = rcsObj.execute(allSelectedIdsList,False,userSelectedContractId,lstAgData);
            } 
        }
        
        FinalOutput finalOut = new FinalOutput();
        finalOut.message = 'Successfully executed';
        finalOut.isSuccess = TRUE;
        lstFinalOut.add(finalOut);
        return lstFinalOut;
    }
    
    public class FinalInput{
        @InvocableVariable(label='user consent' description='user consent after generate preview link is displayed' required=true)
        public Boolean userConsent;
        
        @InvocableVariable(label='selected account id' description='id of the selected account record id' required=true)
        public String accountId;
        
        @InvocableVariable(label='selected contract id' description='id of the selected contract record id' required=true)
        public String contractId;
    }
    public class FinalOutput{
        @InvocableVariable(label='message' description='message for the success or Error' required=true)
        public String message;
        @InvocableVariable(label='is Success' description='Boolean variable if request was success or failed' required=true)
        public Boolean isSuccess;
    }
    
}