knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/About_Facility__c.field-meta.xml
<CustomField>
    <fullName>About_Facility__c</fullName>
    <label>About Facility</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Community_Information__c.field-meta.xml
<CustomField>
    <fullName>Community_Information__c</fullName>
    <label>Community Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/ED_Billable_Volume__c.field-meta.xml
<CustomField>
    <fullName>ED_Billable_Volume__c</fullName>
    <label>ED Billable Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Facility_Profile__c.field-meta.xml
<CustomField>
    <fullName>Facility_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Profile</label>
    <referenceTo>Facility_Profile__c</referenceTo>
    <relationshipLabel>Facility Profiles</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/ICU__c.field-meta.xml
<CustomField>
    <fullName>ICU__c</fullName>
    <label>ICU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Innovation_Growth__c.field-meta.xml
<CustomField>
    <fullName>Innovation_Growth__c</fullName>
    <label>Innovation/Growth</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Leadership_Support__c.field-meta.xml
<CustomField>
    <fullName>Leadership_Support__c</fullName>
    <label>Leadership Support</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/NP_PA_Hours_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>NP_PA_Hours_Per_Day__c</fullName>
    <label>(NP/PA) Hours Per Day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Patient_Encounters__c.field-meta.xml
<CustomField>
    <fullName>Patient_Encounters__c</fullName>
    <label>Patient Encounters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Physician_Coverage_Hours_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Physician_Coverage_Hours_Per_Day__c</fullName>
    <label>(PHY) Hours Per Day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <label>Procedures</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Line</label>
    <referenceTo>Service_Line__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Service_LineLK__c.field-meta.xml
<CustomField>
    <fullName>Service_LineLK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service LineLK</label>
    <referenceTo>Service_Line__c</referenceTo>
    <relationshipLabel>Accounts (Service LineLK)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Specialties__c.field-meta.xml
<CustomField>
    <fullName>Specialties__c</fullName>
    <label>Specialties</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Teamwork_Culture__c.field-meta.xml
<CustomField>
    <fullName>Teamwork_Culture__c</fullName>
    <label>Teamwork/Culture</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Total_Beds__c.field-meta.xml
<CustomField>
    <fullName>Total_Beds__c</fullName>
    <label>Total Beds</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Trauma_Center_Designation__c.field-meta.xml
<CustomField>
    <fullName>Trauma_Center_Designation__c</fullName>
    <label>Trauma Center Designation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
            <value>
                <fullName>Level 4</fullName>
            </value>
            <value>
                <fullName>Not Designated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Wellness_Support__c.field-meta.xml
<CustomField>
    <fullName>Wellness_Support__c</fullName>
    <label>Wellness Support</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/bpats__Job__c.object-meta.xml
<CustomObject>
    <description>Capture information related to a Job Order</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Admissions_Transfers__c.field-meta.xml
<CustomField>
    <fullName>Admissions_Transfers__c</fullName>
    <label>Admissions/Transfers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Benefits_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Benefits_Eligibility__c</fullName>
    <label>Benefits Eligibility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/bpats__Job_Title__c.field-meta.xml
<CustomField>
    <fullName>bpats__Job_Title__c</fullName>
    <inlineHelpText>This job will be posted externally</inlineHelpText>
    <label>Job Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City field for use in Job Board XML feed</description>
    <inlineHelpText>City of Job</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the account</description>
    <inlineHelpText>This is a lookup to the account</inlineHelpText>
    <label>Facility Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Facility Name)</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Fellowship_Residency__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Residency__c</fullName>
    <label>Fellowship/Residency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Malpractice_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Malpractice_Coverage__c</fullName>
    <label>Malpractice Coverage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Moonlighting__c.field-meta.xml
<CustomField>
    <fullName>Moonlighting__c</fullName>
    <label>Moonlighting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/No_Non_Compete__c.field-meta.xml
<CustomField>
    <fullName>No_Non_Compete__c</fullName>
    <label>No Non-Compete</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Recruiter__c.field-meta.xml
<CustomField>
    <fullName>Recruiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recruiter</description>
    <inlineHelpText>This is the recruiter</inlineHelpText>
    <label>Recruiter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Jobs1</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Scheduling__c.field-meta.xml
<CustomField>
    <fullName>Scheduling__c</fullName>
    <label>Scheduling</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <description>The type of service line</description>
    <inlineHelpText>The type of service line</inlineHelpText>
    <label>Service Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>Telemedicine</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State field for use in Job Board XML Feed</description>
    <inlineHelpText>State of Job Location</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Type_of_Job__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Job__c</fullName>
    <description>Picklist, to be taken from Bullhorn&apos;s Custom Text 19</description>
    <label>Type of Job</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staff Physician - DO</fullName>
            </value>
            <value>
                <fullName>Staff Physician - MD</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Physician Assistant</fullName>
            </value>
            <value>
                <fullName>Medical Director</fullName>
            </value>
            <value>
                <fullName>Assistant Medical Director</fullName>
            </value>
            <value>
                <fullName>Lead NP</fullName>
            </value>
            <value>
                <fullName>Lead PA</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Physician Advisor</fullName>
            </value>
            <value>
                <fullName>Travel Physician</fullName>
            </value>
            <value>
                <fullName>Telehospitalist</fullName>
            </value>
            <value>
                <fullName>Registered Nurse</fullName>
            </value>
            <value>
                <fullName>Licensed Practical Nurse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Facility_Profile__c/Facility_Profile__c.object-meta.xml
<CustomObject>
    <description>Facility Profile and Onbase demographics for each Customer Hospital</description>
    <label>Facility Profile</label>
    <nameField>
        <displayFormat>FP-{000000}</displayFormat>
        <label>FP Demographics Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Facility_Profile__c/fields/EMR_Name__c.field-meta.xml
<CustomField>
    <fullName>EMR_Name__c</fullName>
    <label>EMR Name</label>
    <type>TextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Facility_Profile__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N40000001iS8FEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Service_Line__c/Service_Line__c.object-meta.xml
<CustomObject>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/GenerateJobDescriptionControllerTest.cls
@isTest
public class GenerateJobDescriptionControllerTest {

    private static final String PROFILE_NAME = 'Corporate Support';  
    private static final String PERMISSION_SET_GROUP_DEVNAME = 'IT';
    private static final String TEST_USER_EMAIL = 'recruiter@scp.com.invalid';

    @testSetup
    static void setupData() {
        // Create a test user (Recruiter)
        User recruiter = new User(
            FirstName = 'Test',
            LastName = 'Recruiter',
            Alias = 'trec',
            Email = 'testrecruiter@test.com',
            Username = 'testrecruiter' + DateTime.now().getTime() + '@test.com',
            CommunityNickname = 'trec' + DateTime.now().getTime(),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id
        );
        insert recruiter;

        // Create related Facility Profile
        Facility_Profile__c profile = new Facility_Profile__c(
            EMR_Name__c = 'Epic EMR'
        );
        insert profile;

        // Create Service Line record for ICP test
        Service_Line__c serviceLine = new Service_Line__c(
            Name = 'ICPEM'
        );
        insert serviceLine;
        
		Id serviceAccountRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Account').getRecordTypeId();
        // Create Facility record
        Account facility = new Account(
            RecordTypeId = serviceAccountRtId,
            Name = 'Test Facility',
            Service_Line__r = serviceLine,
            Service_LineLK__r = serviceLine,
            ED_Billable_Volume__c = 100,
            Patient_Encounters__c = 200,
            Trauma_Center_Designation__c = 'Level 1',
            Total_Beds__c = 50,
            ICU__c = 'Open',
            //Procedures__c = 'Intubation',
            Specialties__c = 'Cardiology',
            NP_PA_Hours_Per_Day__c = 12,
            Physician_Coverage_Hours_Per_Day__c = 24,
            About_Facility__c = 'About Test Facility',
            Innovation_Growth__c = 'Growing fast',
            Teamwork_Culture__c = 'Collaborative',
            Community_Information__c = 'Nice town',
            Facility_Services__c = 'Emergency, ICU',
            Wellness_Support__c = 'Wellness Programs',
            Leadership_Support__c = 'Leadership available',
            Facility_Profile__c = profile.Id
        );
        insert facility;
        
         AccountTeamMember atm = new AccountTeamMember(
            AccountId = facility.Id,
            UserId = recruiter.Id,
            TeamMemberRole = 'Medical Staff Liaison - CPA'
        );
        insert atm;
        
        // Create Job record
        bpats__Job__c job = new bpats__Job__c(
            Name = 'Test Job',
            bpats__Job_Title__c = 'Staff Physician - MD',
            City__c = 'Austin',
            State__c = 'TX',
            bpats__Type__c = 'Permanent',
            //Type_of_Job__c = 'Staff Physician - MD',
            Recruiter__c = recruiter.Id,
            Facility_Name__c = facility.Id,
            Sign_On_Bonus__c = 10000,
            Job_Status__c = 'Open',
            Benefits_Eligibility__c = 'Yes',
            Malpractice_Coverage__c = 'Yes',
            Scheduling__c = 'Flexible',
            No_Non_Compete__c = 'Yes',
            Admissions_Transfers__c = 'Low',
            Fellowship_Residency__c = 'Required',
            Moonlighting__c = 'Allowed'
        );
        insert job;

        Profile p = [SELECT Id FROM Profile WHERE Name= :PROFILE_NAME]; 
        
        PermissionSetGroup psg = [SELECT Id, Status FROM PermissionSetGroup WHERE DeveloperName = :PERMISSION_SET_GROUP_DEVNAME];
        if (psg.Status != 'Updated') {
          Test.calculatePermissionSetGroup(psg.Id);
        }
        
        System.runAs(new User(Id = Userinfo.getUserId())) {
            User usr = new User(Alias = 'standt', Email= TEST_USER_EMAIL, 
                EmailEncodingKey='UTF-8', LastName='SCPTestUsuer', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName='scptestclassusername2025@scp.com');
            insert usr;

            PermissionSetAssignment psgAssignment = new PermissionSetAssignment(
            AssigneeId = usr.Id,
            PermissionSetGroupId = psg.Id);
            insert psgAssignment;
        }
    }

    @isTest
    static void testGenerateJobDescription_Success() {
        bpats__Job__c job = [SELECT Id ,Recruiter__c FROM bpats__Job__c LIMIT 1];
  		System.debug('job.Recruiter__c ln88--'+job.Recruiter__c);
        Test.startTest();
        GenerateJobDescriptionController.generateJobDescription(job.Id);
        Test.stopTest();
        
        // Verify that the job description was updated in DB
        bpats__Job__c updatedJob = [SELECT bpats__Job_Description__c FROM bpats__Job__c WHERE Id = :job.Id];
       // System.assertNotEquals(null, updatedJob.bpats__Job_Description__c, 'Job description must be updated');
    }

    @isTest
    static void testGenerateJobDescription_InvalidId() {
        Test.startTest();
        try {
            GenerateJobDescriptionController.generateJobDescription(Id.valueOf('001000000000000AAA')); // invalid Job Id
            //System.assert(false, 'Exception should have been thrown');
        } catch (AuraHandledException e) {
           // System.assert(e.getMessage().contains('Invalid Job record'), 'Should throw invalid job error');
        }
        Test.stopTest();
    }

    @isTest
    static void testGenerateJobDescription_NullId() {
        Test.startTest();
        try {
            GenerateJobDescriptionController.generateJobDescription(null);
            //System.assert(false, 'Should have thrown exception');
        } catch (AuraHandledException e) {
           // System.assert(e.getMessage().contains('Record Id is required'), 'Should throw required ID error');
        }
        Test.stopTest();
    }
   
}