knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Global_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_Facility_ID__c</fullName>
    <formula>Global_Account_ID__c</formula>
    <label>Global Facility ID</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Line</label>
    <referenceTo>Service_Line__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Base_Agreement_Date__c.field-meta.xml
<CustomField>
    <fullName>Base_Agreement_Date__c</fullName>
    <description>original cancelled Clinician contract Start Date</description>
    <label>Base Agreement Date</label>
    <type>Date</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Contract_Trigger_Ack__c.field-meta.xml
<CustomField>
    <fullName>Contract_Trigger_Ack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Trigger Ack</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Global_Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Global_Facility_Id__c</fullName>
    <formula>Account.Global_Facility_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Facility Id</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>%/Rate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <label>Service Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>WW</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>VH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Time_Type__c.field-meta.xml
<CustomField>
    <fullName>Time_Type__c</fullName>
    <label>Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Employment_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not applicable</fullName>
            </value>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>PRN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Practice Operations</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Clinician.recordType-meta.xml
<RecordType>
    <fullName>Clinician</fullName>
    <active>true</active>
    <label>Clinician</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Provider_Network_Contract__r.Healthcare_Practitioner_Facility__c , Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Name , &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Healthcare Practitioner Facility</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Provider_Network_Contract__c.field-meta.xml
<CustomField>
    <fullName>Provider_Network_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Network Contract</label>
    <referenceTo>ProviderNetworkContract</referenceTo>
    <relationshipLabel>Contract Payment Agreements</relationshipLabel>
    <relationshipName>Contract_Payment_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stipend</fullName>
            </value>
            <value>
                <fullName>Shift</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Leadership Incentives</fullName>
            </value>
            <value>
                <fullName>Locums</fullName>
                <isActive>false</isActive>
                <label>Locums</label>
            </value>
            <value>
                <fullName>Locums On Call</fullName>
                <isActive>false</isActive>
                <label>Locums On Call</label>
            </value>
            <value>
                <fullName>Locums Travel</fullName>
                <isActive>false</isActive>
                <label>Locums Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Time_Type__c.field-meta.xml
<CustomField>
    <fullName>Time_Type__c</fullName>
    <label>Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>On Call</fullName>
                <label>On-Call</label>
            </value>
            <value>
                <fullName>PRN</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/FacilityTitle__c.field-meta.xml
<CustomField>
    <fullName>FacilityTitle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Title</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>CodeSet.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CodeSet.CodeSetType</field>
            <operation>equals</operation>
            <value>Facility Title</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Preventive Care Agreements (Facility Title)</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements1</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Shift__c.field-meta.xml
<CustomField>
    <fullName>Shift__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shift</label>
    <referenceTo>Shift__c</referenceTo>
    <relationshipLabel>Preventive Care Agreements</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Shift_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Shift_Full_Name__c</fullName>
    <formula>Type__r.Name + &apos; &apos; +  Shift_Iteration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shift Full Name</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Time_Type__c.field-meta.xml
<CustomField>
    <fullName>Time_Type__c</fullName>
    <label>Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Type</valueSetName>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Preventive Care Agreements (Type)</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements2</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>per Metric</fullName>
            </value>
            <value>
                <fullName>% Salary Reduction</fullName>
            </value>
            <value>
                <fullName>per Monthly Tier</fullName>
            </value>
            <value>
                <fullName>per Hour</fullName>
            </value>
            <value>
                <fullName>per Shift</fullName>
            </value>
            <value>
                <fullName>per Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ProviderNetworkContract/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Practitioner Facility</label>
    <referenceTo>HealthcarePractitionerFacility</referenceTo>
    <relationshipLabel>Provider Network Contracts</relationshipLabel>
    <relationshipName>Provider_Network_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ProviderNetworkContract/fields/Number_of_Anticipate_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Anticipate_Hours__c</fullName>
    <label>Number of Anticipate Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Rate_Pay_Code__c/Rate_Pay_Code__c.object-meta.xml
<CustomObject>
    <label>Rate Pay Code</label>
    <nameField>
        <displayFormat>RPC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Pay Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Rate_Pay_Code__c/fields/Preventive_Care_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Preventive_Care_Agreement__c</fullName>
    <label>Preventive Care Agreement</label>
    <referenceTo>PreventiveCareAgreement</referenceTo>
    <relationshipLabel>Rate Pay Codes</relationshipLabel>
    <relationshipName>Rate_Pay_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Service_Line__c/Service_Line__c.object-meta.xml
<CustomObject>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Service_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Line</fullName>
            </value>
            <value>
                <fullName>Parent Service Line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/Shift__c.object-meta.xml
<CustomObject>
    <label>Shift</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Shift Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Shift_Full_Name__c</fullName>
    <formula>Shift_Name__r.Name &amp; &quot; &quot;  &amp;  Shift_Iteration__c</formula>
    <label>Shift Full Name</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NP/PA</fullName>
            </value>
            <value>
                <fullName>MD/DO</fullName>
            </value>
            <value>
                <fullName>RN/LPN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/globalValueSets/Time_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Part Time</fullName>
    </customValue>
    <customValue>
        <fullName>On Call</fullName>
    </customValue>
    <customValue>
        <fullName>PRN</fullName>
    </customValue>
    <customValue>
        <fullName>Locum</fullName>
    </customValue>
    <customValue>
        <fullName>Locums</fullName>
        <isActive>false</isActive>
        <label>Locums</label>
    </customValue>
    <masterLabel>Time Type</masterLabel>
</GlobalValueSet>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/ClinicianContractCloneService.cls
/**
 * @description Service for cloning clinician contracts and related agreements (PNCs, CPAs, PCAs, Rate Pay Codes).
 * Extracted from CloneContractAction for separation of concerns.
 */
public with sharing class ClinicianContractCloneService {

    @TestVisible private static Boolean pncInsertException = false;
    @TestVisible private static Boolean cpaInsertException = false;
    @TestVisible private static Boolean cleanupException = false;
    @TestVisible private static Boolean adjustShiftRatesException = false;
    @TestVisible private static Boolean adjustShiftRatesInnerException = false;
    @TestVisible private static String clientGlobalFacilityId = null;
    @TestVisible private static String clonedGlobalFacilityId = null;

    /**
     * @description Clones clinician contracts and all related agreements including
     * PNCs, CPAs, PCAs, and Rate Pay Codes.
     * @param clinicianIds List of clinician (Contact) Ids - used to find Contracts via Account.PersonContactId
     * @param clientContractId Client contract Id
     * @return List of newly created contract Ids
     */
    public static List<Id> cloneContracts(List<Id> clinicianIds, String clientContractId) {
        List<Id> newlyCreatedContractIds = new List<Id>();

        if (clinicianIds == null || clinicianIds.isEmpty()) {
            return newlyCreatedContractIds;
        }

        List<Contract> contractsToDelete = new List<Contract>();
        List<ProviderNetworkContract> pncsToDelete = new List<ProviderNetworkContract>();
        List<ContractPaymentAgreement> cpasToDelete = new List<ContractPaymentAgreement>();
        List<PreventiveCareAgreement> pcasToDelete = new List<PreventiveCareAgreement>();
        List<Rate_Pay_Code__c> ratePayCodesToDelete = new List<Rate_Pay_Code__c>();

        try {
            Contract clientContract = !String.isBlank(clientContractId)
                ? getClientContractData(clientContractId) : null;

            Map<Id, Contract> latestContractByAccount = new Map<Id, Contract>();
            for (Contract c : fetchOriginalContracts(clinicianIds)) {
                if (!latestContractByAccount.containsKey(c.AccountId)) {
                    latestContractByAccount.put(c.AccountId, c);
                }
            }

            List<Contract> originalContracts = latestContractByAccount.values();

            if (originalContracts.isEmpty()) { return newlyCreatedContractIds; }

            Map<Id, Contract> successfulContractClones =
                cloneAndInsertContracts(originalContracts, clientContract, contractsToDelete, newlyCreatedContractIds);

            if (successfulContractClones.isEmpty()) { return newlyCreatedContractIds; }

            Map<Id, ProviderNetworkContract> successfulPNCClones =
                cloneAndInsertPNCs(successfulContractClones, pncsToDelete, contractsToDelete);

            Map<Id, Id> contractIdMap = buildIdMap(successfulContractClones);
            Map<Id, Id> pncIdMap = buildIdMap(successfulPNCClones);

            createCPAandPCA(contractIdMap, pncIdMap, contractsToDelete, pncsToDelete, cpasToDelete, pcasToDelete, clientContractId);

            cleanupFailedRecords(contractsToDelete, pncsToDelete, cpasToDelete, pcasToDelete, ratePayCodesToDelete);

            return newlyCreatedContractIds;

        } catch (Exception ex) {
            RateChangeNotificationUtil.logError('ClinicianContractCloneService.cloneContracts', null, ex);
            return newlyCreatedContractIds;
        }
    }

    private static Contract getClientContractData(String clientContractId) {
        return [SELECT Id, StartDate, Account.Service_Line__r.Name FROM Contract WHERE Id = :clientContractId];
    }

    private static List<Contract> fetchOriginalContracts(List<Id> clinicianIds) {
        return (List<Contract>) fetchAllFields(
            Contract.SObjectType,
            new Set<Id>(clinicianIds),
            'Account.PersonContactId',
            new Set<String>{ 'Account.Name' }
        );
    }

    private static Map<Id, Contract> cloneAndInsertContracts(
        List<Contract> originalContracts,
        Contract clientContract,
        List<Contract> contractsToDelete,
        List<Id> newlyCreatedContractIds
    ) {
        List<Contract> clonedContracts = new List<Contract>();
        Map<Id, Contract> originalToCloneMap = new Map<Id, Contract>();

        for (Contract original : originalContracts) {
            Date startDate = (clientContract != null && clientContract.StartDate != null)
                ? clientContract.StartDate : Date.today();
            startDate = Test.isRunningTest() ? Date.today() + 120 : startDate;
            Map<String, Object> overrides = new Map<String, Object>{
                'Name' => (original.Account.Name != null ? original.Account.Name : 'Clone') + ' ' + startDate,
                'Status' => 'Draft',
                'StartDate' => startDate,
                'PreviousContractId' => original.Id,
                'RecordTypeId' => original.RecordTypeId,
                'Base_Agreement_Date__c' => original.StartDate,
                'CompanySignedDate' => System.today(),
                'Contract_Trigger_Ack__c' => false
            };
            if (original.AccountId != null) { overrides.put('AccountId', original.AccountId); }
            if (original.Pricebook2Id != null) { overrides.put('Pricebook2Id', original.Pricebook2Id); }
            if (original.ContractTerm != null) { overrides.put('ContractTerm', original.ContractTerm); }

            Contract clone = (Contract) dynamicClone(original, new List<String>{ 'Id' }, overrides);
            clonedContracts.add(clone);
            originalToCloneMap.put(original.Id, clone);
        }

        Map<Id, Contract> successfulContractClones = new Map<Id, Contract>();
        Database.SaveResult[] results = Database.insert(clonedContracts, false);

        for (Integer i = 0; i < results.size(); i++) {
            if (results[i].isSuccess()) {
                successfulContractClones.put(originalContracts[i].Id, clonedContracts[i]);
                newlyCreatedContractIds.add(clonedContracts[i].Id);
            } else {
                RateChangeNotificationUtil.logError('Contract Insert Failed', originalContracts[i].Id, results[i].getErrors());
                contractsToDelete.add(clonedContracts[i]);
            }
        }

        return successfulContractClones;
    }

    private static Map<Id, ProviderNetworkContract> cloneAndInsertPNCs(
        Map<Id, Contract> successfulContractClones,
        List<ProviderNetworkContract> pncsToDelete,
        List<Contract> contractsToDelete
    ) {
        Map<Id, ProviderNetworkContract> successfulPNCClones = new Map<Id, ProviderNetworkContract>();
        if (successfulContractClones.isEmpty()) { return successfulPNCClones; }

        Set<Id> successfulContractIds = successfulContractClones.keySet();
        List<ProviderNetworkContract> originalPNCs = (List<ProviderNetworkContract>) fetchAllFields(
            ProviderNetworkContract.SObjectType,
            successfulContractIds,
            'ContractId'
        );

        if (originalPNCs.isEmpty()) { return successfulPNCClones; }

        List<ProviderNetworkContract> clonedPNCs = new List<ProviderNetworkContract>();
        for (ProviderNetworkContract pnc : originalPNCs) {
            Contract clonedContract = successfulContractClones.get(pnc.ContractId);
            if (clonedContract == null) {
                continue;
            }

            Date startDate = clonedContract.StartDate != null ? clonedContract.StartDate : Date.today();
            Date endDate = (clonedContract.EndDate == null || clonedContract.EndDate < startDate)
                ? startDate.addMonths(12) : clonedContract.EndDate;

            Map<String, Object> overrides = new Map<String, Object>{
                'ContractId' => clonedContract.Id,
                'StartDate' => startDate,
                'EndDate' => endDate
            };
            if (pnc.HealthcarePayerNetworkId != null) { overrides.put('HealthcarePayerNetworkId', pnc.HealthcarePayerNetworkId); }
            if (pnc.HealthcareProviderId != null) { overrides.put('HealthcareProviderId', pnc.HealthcareProviderId); }
            if (pnc.Healthcare_Practitioner_Facility__c != null) { overrides.put('Healthcare_Practitioner_Facility__c', pnc.Healthcare_Practitioner_Facility__c); }
            if (pnc.Number_of_Anticipate_Hours__c != null) { overrides.put('Number_of_Anticipate_Hours__c', pnc.Number_of_Anticipate_Hours__c); }

            ProviderNetworkContract clone = (ProviderNetworkContract) dynamicClone(
                pnc,
                new List<String>{ 'Id', 'ContractId' },
                overrides
            );
            clonedPNCs.add(clone);
        }

        if (Test.isRunningTest() && pncInsertException && !clonedPNCs.isEmpty()) {
            clonedPNCs[0].ContractId = null;
        }
        Database.SaveResult[] pncResults = Database.insert(clonedPNCs, false);
        for (Integer i = 0; i < pncResults.size(); i++) {
            if (pncResults[i].isSuccess()) {
                successfulPNCClones.put(originalPNCs[i].Id, clonedPNCs[i]);
            } else {
                RateChangeNotificationUtil.logError('PNC Insert Failed', originalPNCs[i].Id, pncResults[i].getErrors());
                pncsToDelete.add(clonedPNCs[i]);
                Id failedContractId = originalPNCs[i].ContractId;
                if (successfulContractClones.containsKey(failedContractId)) {
                    contractsToDelete.add(successfulContractClones.get(failedContractId));
                    successfulContractClones.remove(failedContractId);
                }
            }
        }
        return successfulPNCClones;
    }

    private static Map<Id, Id> buildIdMap(Map<Id, SObject> cloneMap) {
        Map<Id, Id> idMap = new Map<Id, Id>();
        for (Id oldId : cloneMap.keySet()) {
            idMap.put(oldId, cloneMap.get(oldId).Id);
        }
        return idMap;
    }

    private static void createCPAandPCA(
        Map<Id, Id> oldToNewContractMap,
        Map<Id, Id> oldToNewPNCMap,
        List<Contract> contractsToDelete,
        List<ProviderNetworkContract> pncsToDelete,
        List<ContractPaymentAgreement> cpasToDelete,
        List<PreventiveCareAgreement> pcasToDelete,
        String clientContractId
    ) {
        try {
            if (oldToNewContractMap.isEmpty()) {
                RateChangeNotificationUtil.logError('ClinicianContractCloneService.createCPAandPCA', null, 'No contract mappings found, skipping CPA/PCA cloning.');
                return;
            }

            Map<Id, Contract> newContractMap = fetchNewContracts(oldToNewContractMap.values());
            Map<Id, Account> accountMap = fetchAccounts(newContractMap.values());
            List<ContractPaymentAgreement> originalCPAs = fetchOriginalCPAs(oldToNewContractMap.keySet());
            if (originalCPAs.isEmpty()) { return; }

            Map<Id, ProviderNetworkContract> pncMap = fetchPNCsForCPAs(originalCPAs);

            Map<Id, Id> oldCPAtoNewCPA = cloneCPAs(
                originalCPAs,
                oldToNewContractMap,
                oldToNewPNCMap,
                newContractMap,
                accountMap,
                contractsToDelete,
                cpasToDelete
            );
            if (oldCPAtoNewCPA.isEmpty()) { return; }

            List<Rate_Pay_Code__c> ratePayCodesToDelete = new List<Rate_Pay_Code__c>();
            Map<Id, List<PreventiveCareAgreement>> oldToNewPcaMap = clonePCAs(oldCPAtoNewCPA, pcasToDelete);

            cloneRatePayCodesForPCAs(oldToNewPcaMap, ratePayCodesToDelete);

            List<PreventiveCareAgreement> allClonedPCAs = new List<PreventiveCareAgreement>();
            for (List<PreventiveCareAgreement> pcaList : oldToNewPcaMap.values()) {
                allClonedPCAs.addAll(pcaList);
            }

            if (!allClonedPCAs.isEmpty() && !String.isBlank(clientContractId)) {
                adjustShiftRates(allClonedPCAs, clientContractId);
            }
        } catch (Exception ex) {
            RateChangeNotificationUtil.logError('ClinicianContractCloneService.createCPAandPCA', null, ex);
        }
    }

    private static void cleanupFailedRecords(
        List<Contract> contractsToDelete,
        List<ProviderNetworkContract> pncsToDelete,
        List<ContractPaymentAgreement> cpasToDelete,
        List<PreventiveCareAgreement> pcasToDelete,
        List<Rate_Pay_Code__c> ratePayCodesToDelete
    ) {
        try {
            if (Test.isRunningTest() && cleanupException) {
                throw new DmlException('test');
            }
            if (!ratePayCodesToDelete.isEmpty()) { delete ratePayCodesToDelete; }
            if (!pcasToDelete.isEmpty()) { delete pcasToDelete; }
            if (!cpasToDelete.isEmpty()) { delete cpasToDelete; }
            if (!pncsToDelete.isEmpty()) { delete pncsToDelete; }
            if (!contractsToDelete.isEmpty()) { delete contractsToDelete; }
        } catch (DmlException cleanupEx) {
            RateChangeNotificationUtil.logError('Cleanup Failed', null, cleanupEx);
        }
    }

    private static Map<Id, Contract> fetchNewContracts(List<Id> newContractIds) {
        return new Map<Id, Contract>([
            SELECT Id, ContractNumber, AccountId, StartDate
            FROM Contract
            WHERE Id IN :newContractIds
        ]);
    }

    private static Map<Id, Account> fetchAccounts(List<Contract> contracts) {
        Set<Id> accountIds = new Set<Id>();
        for (Contract c : contracts) {
            if (c.AccountId != null) {
                accountIds.add(c.AccountId);
            }
        }
        if (accountIds.isEmpty()) {
            return new Map<Id, Account>();
        }

        return new Map<Id, Account>([
            SELECT Id, Global_Provider_ID__pc, Name
            FROM Account
            WHERE Id IN :accountIds
        ]);
    }

    private static List<ContractPaymentAgreement> fetchOriginalCPAs(Set<Id> contractIds) {
        Set<String> extraFieldSet = new Set<String>{ 'Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Name' };
        return (List<ContractPaymentAgreement>) fetchAllFields(
            ContractPaymentAgreement.SObjectType,
            contractIds,
            'ContractId',
            extraFieldSet
        );
    }

    private static Map<Id, ProviderNetworkContract> fetchPNCsForCPAs(List<ContractPaymentAgreement> cpas) {
        Set<Id> pncIds = new Set<Id>();
        for (ContractPaymentAgreement cpa : cpas) {
            if (cpa.Provider_Network_Contract__c != null) {
                pncIds.add(cpa.Provider_Network_Contract__c);
            }
        }
        if (pncIds.isEmpty()) {
            return new Map<Id, ProviderNetworkContract>();
        }

        return new Map<Id, ProviderNetworkContract>([
            SELECT Id, Healthcare_Practitioner_Facility__r.Account.Global_Facility_ID__c
            FROM ProviderNetworkContract
            WHERE Id IN :pncIds
        ]);
    }

    private static Map<Id, Id> cloneCPAs(
        List<ContractPaymentAgreement> originalCPAs,
        Map<Id, Id> oldToNewContractMap,
        Map<Id, Id> oldToNewPNCMap,
        Map<Id, Contract> newContractMap,
        Map<Id, Account> accountMap,
        List<Contract> contractsToDelete,
        List<ContractPaymentAgreement> cpasToDelete
    ) {
        List<ContractPaymentAgreement> clonedCPAs = new List<ContractPaymentAgreement>();
        Map<Id, Id> oldCPAtoNewCPA = new Map<Id, Id>();

        for (ContractPaymentAgreement cpa : originalCPAs) {
            if (!oldToNewContractMap.containsKey(cpa.ContractId)) {
                continue;
            }

            Contract newContract = newContractMap.get(oldToNewContractMap.get(cpa.ContractId));
            Account acc = accountMap.get(newContract.AccountId);
            String uniqueName = buildCPAUniqueName(cpa, newContract, acc);

            Map<String, Object> overrides = new Map<String, Object>{
                'ContractId' => oldToNewContractMap.get(cpa.ContractId),
                'Provider_Network_Contract__c' => oldToNewPNCMap.get(cpa.Provider_Network_Contract__c),
                'Status' => 'Draft',
                'Name' => uniqueName,
                'ContractPaymentAgreementKey' => null,
                'StartDateTime' => DateTime.newInstance(newContract.StartDate.year(), newContract.StartDate.month(), newContract.StartDate.day(), 15, 0, 0)
            };

            clonedCPAs.add((ContractPaymentAgreement) dynamicClone(
                cpa, new List<String>{ 'Id', 'ContractId', 'Provider_Network_Contract__c', 'Status', 'Name' }, overrides));
        }

        if (Test.isRunningTest() && cpaInsertException && !clonedCPAs.isEmpty()) {
            clonedCPAs[0].ContractId = null;
        }
        Database.SaveResult[] cpaResults = Database.insert(clonedCPAs, false);
        for (Integer i = 0; i < cpaResults.size(); i++) {
            if (cpaResults[i].isSuccess()) {
                oldCPAtoNewCPA.put(originalCPAs[i].Id, cpaResults[i].getId());
            } else {
                RateChangeNotificationUtil.logError('CPA Insert Failed', null, cpaResults[i].getErrors());
                if (clonedCPAs[i].Id != null) {
                    cpasToDelete.add(clonedCPAs[i]);
                }
                Id parentContractId = oldToNewContractMap.get(originalCPAs[i].ContractId);
                if (parentContractId != null) {
                    contractsToDelete.add(new Contract(Id = parentContractId));
                }
            }
        }
        return oldCPAtoNewCPA;
    }

    private static Map<Id, List<PreventiveCareAgreement>> clonePCAs(
        Map<Id, Id> oldCPAtoNewCPA,
        List<PreventiveCareAgreement> pcasToDelete
    ) {
        Map<Id, List<PreventiveCareAgreement>> oldToNewPcaMap = new Map<Id, List<PreventiveCareAgreement>>();

        List<PreventiveCareAgreement> originalPCAs = (List<PreventiveCareAgreement>) fetchAllFields(
            PreventiveCareAgreement.SObjectType,
            oldCPAtoNewCPA.keySet(),
            'ContractPaymentAgreementId'
        );

        List<PreventiveCareAgreement> clonedPCAs = new List<PreventiveCareAgreement>();

        for (PreventiveCareAgreement pca : originalPCAs) {
            Id newCpaId = oldCPAtoNewCPA.get(pca.ContractPaymentAgreementId);
            if (newCpaId == null) {
                continue;
            }

            Map<String, Object> overrides = new Map<String, Object>{
                'ContractPaymentAgreementId' => oldCPAtoNewCPA.get(pca.ContractPaymentAgreementId)
            };

            PreventiveCareAgreement clonedPca = (PreventiveCareAgreement) dynamicClone(
                pca, new List<String>{ 'Id', 'ContractPaymentAgreementId' }, overrides
            );

            clonedPCAs.add(clonedPca);

            if (!oldToNewPcaMap.containsKey(pca.Id)) {
                oldToNewPcaMap.put(pca.Id, new List<PreventiveCareAgreement>());
            }
            oldToNewPcaMap.get(pca.Id).add(clonedPca);
        }

        Database.SaveResult[] pcaResults = Database.insert(clonedPCAs, false);
        for (Integer i = 0; i < pcaResults.size(); i++) {
            if (!pcaResults[i].isSuccess()) {
                RateChangeNotificationUtil.logError('PCA Insert Failed', null, pcaResults[i].getErrors());
                if (clonedPCAs[i].Id != null) {
                    pcasToDelete.add(clonedPCAs[i]);
                }
            }
        }
        return oldToNewPcaMap;
    }

    private static String buildCPAUniqueName(ContractPaymentAgreement cpa, Contract newContract, Account acc) {
        String globalOrAccount = acc != null && acc.Global_Provider_ID__pc != null ? String.valueOf(acc.Global_Provider_ID__pc) : (acc != null ? acc.Name : 'NA');
        String facilityName = (cpa.Provider_Network_Contract__r != null && cpa.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r != null)
            ? cpa.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Name
            : 'NA';
        return (newContract.ContractNumber != null ? newContract.ContractNumber : 'NA')
            + '-' + globalOrAccount
            + '-' + facilityName
            + '-' + (cpa.Type__c != null ? cpa.Type__c : 'NA');
    }

    @TestVisible
    private static void cloneRatePayCodesForPCAs(Map<Id, List<PreventiveCareAgreement>> oldToNewPcaMap, List<Rate_Pay_Code__c> ratePayCodesToDelete) {
        if (oldToNewPcaMap.isEmpty()) {
            return;
        }

        Set<Id> oldPcaIds = oldToNewPcaMap.keySet();

        List<Rate_Pay_Code__c> originalRatePayCodes = (List<Rate_Pay_Code__c>) fetchAllFields(
            Rate_Pay_Code__c.SObjectType,
            oldPcaIds,
            'Preventive_Care_Agreement__c'
        );

        List<Rate_Pay_Code__c> clones = new List<Rate_Pay_Code__c>();

        for (Rate_Pay_Code__c original : originalRatePayCodes) {
            List<PreventiveCareAgreement> newPcas = oldToNewPcaMap.get(original.Preventive_Care_Agreement__c);
            if (newPcas == null || newPcas.isEmpty()) {
                continue;
            }

            for (PreventiveCareAgreement newPca : newPcas) {
                Map<String, Object> overrides = new Map<String, Object>{
                    'Preventive_Care_Agreement__c' => newPca.Id
                };

                Rate_Pay_Code__c clone = (Rate_Pay_Code__c) dynamicClone(
                    original,
                    new List<String>{ 'Id', 'Preventive_Care_Agreement__c' },
                    overrides
                );
                clones.add(clone);
            }
        }

        if (!clones.isEmpty()) {
            Database.SaveResult[] saveResults = Database.insert(clones, false);
            for (Integer i = 0; i < saveResults.size(); i++) {
                if (!saveResults[i].isSuccess()) {
                    RateChangeNotificationUtil.logError('RatePayrec Insert Failed', null, saveResults[i].getErrors());
                    if (clones[i].Id != null) {
                        ratePayCodesToDelete.add(clones[i]);
                    }
                }
            }
        }
    }

    @TestVisible
    private static void adjustShiftRates(List<PreventiveCareAgreement> clonedPCAs, String clientContractId) {
        if (clonedPCAs.isEmpty() || clientContractId == null) {
            return;
        }

        try {
            if (Test.isRunningTest() && adjustShiftRatesException) {
                throw new CalloutException('test');
            }
            List<PreventiveCareAgreement> clientShiftPCAs = [
                SELECT Id, FacilityTitle__r.Name, Shift__r.Shift_Full_Name__c, Rate__c, Unit_of_Measure__c, Time_Type__c,
                    ContractPaymentAgreement.Type__c,
                    ContractPaymentAgreement.Contract.Account.Global_Facility_ID__c
                FROM PreventiveCareAgreement
                WHERE ContractPaymentAgreement.ContractId = :clientContractId
                AND ContractPaymentAgreement.Type__c = 'Shift'
            ];

            Map<String, PreventiveCareAgreement> clientShiftPcaMap = new Map<String, PreventiveCareAgreement>();
            for (PreventiveCareAgreement pca : clientShiftPCAs) {
                if (pca.Shift__r != null && pca.FacilityTitle__r != null) {
                    String globalFacilityId = (Test.isRunningTest() && clientGlobalFacilityId != null)
                        ? clientGlobalFacilityId
                        : (pca.ContractPaymentAgreement.Contract.Account.Global_Facility_ID__c != null
                            ? String.valueOf(pca.ContractPaymentAgreement.Contract.Account.Global_Facility_ID__c) : '');
                    String key = pca.Shift__r.Shift_Full_Name__c + '_' + globalFacilityId + '_' + pca.FacilityTitle__r.Name + '_' + pca.Time_Type__c;
                    clientShiftPcaMap.put(key, pca);
                }
            }

            if (clientShiftPcaMap.isEmpty()) {
                return;
            }

            List<PreventiveCareAgreement> reloadedClonedPCAs = [
                SELECT Id, FacilityTitle__r.Name, Shift__r.Shift_Full_Name__c,
                    ContractPaymentAgreement.Type__c, Time_Type__c,
                    ContractPaymentAgreement.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Account.Global_Facility_ID__c
                FROM PreventiveCareAgreement
                WHERE Id IN :clonedPCAs
            ];

            List<PreventiveCareAgreement> pcasToUpdate = new List<PreventiveCareAgreement>();
            for (PreventiveCareAgreement clonedPca : reloadedClonedPCAs) {
                try {
                    if (Test.isRunningTest() && adjustShiftRatesInnerException) {
                        throw new CalloutException('test');
                    }
                    if (clonedPca.ContractPaymentAgreement.Type__c == 'Shift' &&
                        clonedPca.Shift__r != null &&
                        clonedPca.FacilityTitle__r != null) {
                        String globalFacilityId = (Test.isRunningTest() && clonedGlobalFacilityId != null)
                            ? clonedGlobalFacilityId
                            : (clonedPca.ContractPaymentAgreement.Provider_Network_Contract__r != null
                                && clonedPca.ContractPaymentAgreement.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r != null
                                && clonedPca.ContractPaymentAgreement.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Account.Global_Facility_ID__c != null
                                ? String.valueOf(clonedPca.ContractPaymentAgreement.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Account.Global_Facility_ID__c)
                                : '');
                        String key = clonedPca.Shift__r.Shift_Full_Name__c + '_' + globalFacilityId + '_' + clonedPca.FacilityTitle__r.Name + '_' + clonedPca.Time_Type__c;
                        if (clientShiftPcaMap.containsKey(key)) {
                            PreventiveCareAgreement clientPca = clientShiftPcaMap.get(key);
                            PreventiveCareAgreement cloneToUpdate = new PreventiveCareAgreement(
                                Id = clonedPca.Id,
                                Rate__c = clientPca.Rate__c,
                                Unit_of_Measure__c = clientPca.Unit_of_Measure__c
                            );
                            pcasToUpdate.add(cloneToUpdate);
                        }
                    }
                } catch (Exception innerEx) {
                    RateChangeNotificationUtil.logError('Shift PCA mapping failed for PCA ' + clonedPca.Id, null, innerEx);
                }
            }

            if (!pcasToUpdate.isEmpty()) {
                update pcasToUpdate;
            }

        } catch (Exception ex) {
            RateChangeNotificationUtil.logError('ClinicianContractCloneService.adjustShiftRates failed', null, ex);
        }
    }

    /**
     * @description Fetches all createable/updateable fields for records matching the filter.
     * For Contract SObjectType, adds Status = 'Executed' filter.
     */
    private static List<SObject> fetchAllFields(SObjectType sObjectType, Set<Id> filterIds, String filterFieldName) {
        return fetchAllFields(sObjectType, filterIds, filterFieldName, null);
    }

    /**
     * @description Fetches all fields plus optional extra related fields for records matching the filter.
     * For Contract SObjectType, adds Status = 'Executed' and orders by AccountId, StartDate DESC.
     */
    private static List<SObject> fetchAllFields(SObjectType sObjectType, Set<Id> filterIds, String filterFieldName, Set<String> extraFields) {
        if (filterIds == null || filterIds.isEmpty()) {
            return new List<SObject>();
        }

        Map<String, Schema.SObjectField> fieldMap = sObjectType.getDescribe().fields.getMap();
        List<String> fieldNames = new List<String>();
        for (String fName : fieldMap.keySet()) {
            fieldNames.add(fName);
        }

        if (extraFields != null && !extraFields.isEmpty()) {
            fieldNames.addAll(extraFields);
        }

        String query;
        if (sObjectType == Contract.SObjectType) {
            query = 'SELECT ' + String.join(fieldNames, ',') +
                ' FROM ' + sObjectType.getDescribe().getName() +
                ' WHERE ' + filterFieldName + ' IN :filterIds AND Status = \'Executed\'';
            if (extraFields != null && !extraFields.isEmpty()) {
                query += ' ORDER BY AccountId, StartDate DESC';
            }
        } else {
            query = 'SELECT ' + String.join(fieldNames, ',') +
                ' FROM ' + sObjectType.getDescribe().getName() +
                ' WHERE ' + filterFieldName + ' IN :filterIds';
        }

        return Database.query(query);
    }

    /**
     * @description Creates a clone of an SObject, copying all createable/updateable fields except those in excludeFields.
     */
    private static SObject dynamicClone(SObject original, List<String> excludeFields, Map<String, Object> overrideValues) {
        SObject clone = original.getSObjectType().newSObject();
        Map<String, Schema.SObjectField> fieldMap = original.getSObjectType().getDescribe().fields.getMap();

        for (String fieldName : fieldMap.keySet()) {
            Schema.DescribeFieldResult fieldDesc = fieldMap.get(fieldName).getDescribe();
            if (fieldDesc.isCreateable() && fieldDesc.isUpdateable() && !excludeFields.contains(fieldName)) {
                clone.put(fieldName, original.get(fieldName));
            }
        }

        if (overrideValues != null) {
            for (String key : overrideValues.keySet()) {
                clone.put(key, overrideValues.get(key));
            }
        }
        return clone;
    }
}