knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Line</label>
    <referenceTo>Service_Line__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/Clinical_Rate_Change__c.object-meta.xml
<CustomObject>
    <label>Clinical Rate Change</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Clinical Rate Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Rate Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <description>stores the Contract Id of user selected Contract.</description>
    <label>Contract ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/DocGenerationBatchProcessId__c.field-meta.xml
<CustomField>
    <fullName>DocGenerationBatchProcessId__c</fullName>
    <description>used to capture the DocGenerationBatchProcessId</description>
    <label>DocGenerationBatchProcessId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/PreviewClonedContractIds__c.field-meta.xml
<CustomField>
    <fullName>PreviewClonedContractIds__c</fullName>
    <description>Used to capture the Clone contracts via preview code(can be max 2 ids based on professional Title).</description>
    <label>PreviewClonedContractIds</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/Service_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_ID__c</fullName>
    <description>stores the Id of user selected Facility</description>
    <label>Service Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Contracting_Corporate_Entity__c.field-meta.xml
<CustomField>
    <fullName>Contracting_Corporate_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Corporate Entity on the Clinician’s Contract</inlineHelpText>
    <label>Contracting Corporate Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeName__c</field>
            <operation>equals</operation>
            <value>Corporate_Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Contracting Corporate Entity)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/EE_NP_PA_Full_Time_Monthly_Blended__c.field-meta.xml
<CustomField>
    <fullName>EE_NP_PA_Full_Time_Monthly_Blended__c</fullName>
    <label>EE NP/PA Full Time Monthly Blended</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/EE_NP_PA_Full_Time_Overage_Rate__c.field-meta.xml
<CustomField>
    <fullName>EE_NP_PA_Full_Time_Overage_Rate__c</fullName>
    <label>EE NP/PA Full Time Overage Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/EE_NP_PA_Hourly_Blended__c.field-meta.xml
<CustomField>
    <fullName>EE_NP_PA_Hourly_Blended__c</fullName>
    <label>EE NP/PA Hourly Blended</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/NPPA_Tier__c.field-meta.xml
<CustomField>
    <fullName>NPPA_Tier__c</fullName>
    <label>NPPA Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>168</fullName>
            </value>
            <value>
                <fullName>162</fullName>
                <isActive>false</isActive>
                <label>162</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>%/Rate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <label>Service Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>WW</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>VH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Practice Operations</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Clinician.recordType-meta.xml
<RecordType>
    <fullName>Clinician</fullName>
    <active>true</active>
    <label>Clinician</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Provider_Network_Contract__r.Healthcare_Practitioner_Facility__c , Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Name , &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Healthcare Practitioner Facility</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Provider_Network_Contract__c.field-meta.xml
<CustomField>
    <fullName>Provider_Network_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Network Contract</label>
    <referenceTo>ProviderNetworkContract</referenceTo>
    <relationshipLabel>Contract Payment Agreements</relationshipLabel>
    <relationshipName>Contract_Payment_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stipend</fullName>
            </value>
            <value>
                <fullName>Shift</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Leadership Incentives</fullName>
            </value>
            <value>
                <fullName>Locums</fullName>
                <isActive>false</isActive>
                <label>Locums</label>
            </value>
            <value>
                <fullName>Locums On Call</fullName>
                <isActive>false</isActive>
                <label>Locums On Call</label>
            </value>
            <value>
                <fullName>Locums Travel</fullName>
                <isActive>false</isActive>
                <label>Locums Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Contracting_Corporate_Entity__c.field-meta.xml
<CustomField>
    <fullName>Contracting_Corporate_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contracting Corporate Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeName__c</field>
            <operation>equals</operation>
            <value>Corporate_Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcare Practitioner Facilities</relationshipLabel>
    <relationshipName>Healthcare_Practitioner_Facilities</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/EE_NP_PA_Hourly_Blended__c.field-meta.xml
<CustomField>
    <fullName>EE_NP_PA_Hourly_Blended__c</fullName>
    <description>Created as part of PR1050558-4998</description>
    <formula>IF(
    OR(
        ISBLANK(ContractPaymentAgreement.Contract.EE_NP_PA_Hourly_Blended__c),
        ContractPaymentAgreement.Contract.EE_NP_PA_Hourly_Blended__c == 0
    ),
    0,
    IF(
        ISBLANK(Shift__c),
        0,
        IF(
            AND(
                NOT(ISBLANK(Shift__c)),
                Shift__r.Shift_Name__r.Name &lt;&gt; &quot;Shift Bonus&quot;
            ),
            ContractPaymentAgreement.Contract.EE_NP_PA_Hourly_Blended__c,
            0
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EE NP/PA Hourly Blended</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Shift__c.field-meta.xml
<CustomField>
    <fullName>Shift__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shift</label>
    <referenceTo>Shift__c</referenceTo>
    <relationshipLabel>Preventive Care Agreements</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Shift_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Shift_Full_Name__c</fullName>
    <formula>Type__r.Name + &apos; &apos; +  Shift_Iteration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shift Full Name</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Preventive Care Agreements (Type)</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements2</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>per Metric</fullName>
            </value>
            <value>
                <fullName>% Salary Reduction</fullName>
            </value>
            <value>
                <fullName>per Monthly Tier</fullName>
            </value>
            <value>
                <fullName>per Hour</fullName>
            </value>
            <value>
                <fullName>per Shift</fullName>
            </value>
            <value>
                <fullName>per Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ProviderNetworkContract/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Practitioner Facility</label>
    <referenceTo>HealthcarePractitionerFacility</referenceTo>
    <relationshipLabel>Provider Network Contracts</relationshipLabel>
    <relationshipName>Provider_Network_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Service_Line__c/Service_Line__c.object-meta.xml
<CustomObject>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Service_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Line</fullName>
            </value>
            <value>
                <fullName>Parent Service Line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/Shift__c.object-meta.xml
<CustomObject>
    <label>Shift</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Shift Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Shift_Full_Name__c</fullName>
    <formula>Shift_Name__r.Name &amp; &quot; &quot;  &amp;  Shift_Iteration__c</formula>
    <label>Shift Full Name</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/GenerateLetterService.cls
/**
 * @description Service for generating and attaching rate change notice documents to clinician contracts.
 * Extracted from CloneContractAction for separation of concerns.
 */
global with sharing class GenerateLetterService {

    @TestVisible private static Boolean letterGenerationFailure = false;
    @TestVisible private static GenerateAndAttachLetterResult letterResult = null;
    @TestVisible private static Boolean generateAndAttachLetterException = false;
    @TestVisible private static Boolean buildTokenDataException = false;
    @TestVisible private static Boolean buildTokenDataUseQueryInCatch = false;
    @TestVisible private static Boolean buildDGPAlwaysReturnsDGP = false;
    @TestVisible private static Boolean createBatchProcessSObjectException = false;

    /**
     * @description Result of generateAndAttachLetter.
     */
    global class GenerateAndAttachLetterResult {
        global Boolean success;
        global Id batchProcessId;
    }

    /**
     * @description Wrapper holding client contract and related identifiers for document generation.
     */
    public class ClientContractWrapper {
        public Contract contract;
        public String serviceAccountId;
        public String clinicalContractId;
    }

    /**
     * @description Generates and attaches rate change notice documents to clinician contracts.
     * @param clinicianContractIds List of clinician contract Ids
     * @param previewedContracts Clinical_Rate_Change__c records with Service_Account_ID__c and Contract_ID__c
     * @param useBatchProcess Whether to create DocGenerationBatchProcess for batch tracking
     * @return GenerateAndAttachLetterResult with success and batchProcessId (when useBatchProcess is true)
     */
    global static GenerateAndAttachLetterResult generateAndAttachLetter(
        List<Id> clinicianContractIds,
        List<Clinical_Rate_Change__c> previewedContracts,
        Boolean useBatchProcess
    ) {
        GenerateAndAttachLetterResult result = new GenerateAndAttachLetterResult();
        result.success = false;
        result.batchProcessId = null;

        if (clinicianContractIds == null || clinicianContractIds.isEmpty()) {
            return result;
        }

        if (Test.isRunningTest() && letterGenerationFailure) {
            return result;
        }
        if (Test.isRunningTest() && letterResult != null) {
            return letterResult;
        }

        try {
            if (Test.isRunningTest() && generateAndAttachLetterException) {
                throw new CalloutException('test');
            }
            ClientContractWrapper wrapper = fetchClientContractData(previewedContracts);

            Map<Id, String> hpaMap = fetchHpaMapping(previewedContracts, wrapper.serviceAccountId);

            List<Contract> contracts = fetchContracts(clinicianContractIds);
            if (contracts.isEmpty()) {
                return result;
            }

            Map<String, Id> templateMap = fetchTemplates();

            DocGenerationBatchProcess batchProcess = useBatchProcess ? createBatchProcess(previewedContracts, wrapper.serviceAccountId, wrapper.clinicalContractId) : null;

            Map<String, List<Object>> facilityShiftTable = getFacilityRateData(clinicianContractIds);

            List<DocumentGenerationProcess> dgpList = new List<DocumentGenerationProcess>();
            for (Contract contract : contracts) {
                DocumentGenerationProcess dgp = buildDGP(contract, wrapper.contract, hpaMap, templateMap, facilityShiftTable, batchProcess);
                if (dgp != null) {
                    dgpList.add(dgp);
                }
            }

            if (!dgpList.isEmpty()) {
                insert dgpList;
                if (batchProcess != null) { batchProcess.Status = 'InProgress'; update batchProcess; }
                result.success = true;
                result.batchProcessId = batchProcess != null ? batchProcess.Id : null;
            }

        } catch (Exception e) {
            RateChangeNotificationUtil.logError('GenerateLetterService.generateAndAttachLetter', null, e);
        }
        return result;
    }

    /**
     * @description Fetches client contract wrapper from Clinical_Rate_Change__c records.
     * @param previewedContracts Clinical_Rate_Change__c records with Service_Account_ID__c and Contract_ID__c
     * @return ClientContractWrapper with contract, serviceAccountId, clinicalContractId
     */
    @TestVisible private static ClientContractWrapper fetchClientContractData(List<Clinical_Rate_Change__c> previewedContracts) {
        ClientContractWrapper wrapper = new ClientContractWrapper();
        if (!previewedContracts.isEmpty()) {
            wrapper.serviceAccountId = previewedContracts[0].Service_Account_ID__c;
            wrapper.clinicalContractId = previewedContracts[0].Contract_ID__c;
            if (!String.isBlank(wrapper.clinicalContractId)) {
                wrapper.contract = getClientContractData(wrapper.clinicalContractId);
            }
        }
        return wrapper;
    }

    private static Contract getClientContractData(String clientContractId) {
        return [SELECT Id, StartDate, Account.Service_Line__r.Name FROM Contract WHERE Id = :clientContractId];
    }

    private static Map<Id, String> fetchHpaMapping(List<Clinical_Rate_Change__c> previewedContracts, String serviceAccountId) {
        List<Id> selectedClinicians = previewedContracts.isEmpty() ? new List<Id>() : getSelectedClinicianIds(previewedContracts);
        return getHpaRecordsForClinicians(selectedClinicians, serviceAccountId);
    }

    private static Map<String, Id> fetchTemplates() {
        Map<String, Id> templateMap = new Map<String, Id>();
        for (DocumentTemplateContentDoc doc : [
            SELECT LatestContentVersionId, DocumentTemplate.Name
            FROM DocumentTemplateContentDoc
            WHERE DocumentTemplate.Name IN ('RateChangeNoticeEEFTNPPA', 'RateChangeNoticeEEFMD')
        ]) {
            templateMap.put(doc.DocumentTemplate.Name, doc.LatestContentVersionId);
        }
        if (Test.isRunningTest() && (!templateMap.containsKey('RateChangeNoticeEEFTNPPA') || !templateMap.containsKey('RateChangeNoticeEEFMD'))) {
            ContentVersion cv = new ContentVersion(
                Title = 'RateChangeNoticeEEFMD',
                PathOnClient = 'test.docx',
                VersionData = Blob.valueOf('Test')
            );
            insert cv;
            cv = [SELECT Id FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
            if (!templateMap.containsKey('RateChangeNoticeEEFTNPPA')) {
                templateMap.put('RateChangeNoticeEEFTNPPA', cv.Id);
            }
            if (!templateMap.containsKey('RateChangeNoticeEEFMD')) {
                templateMap.put('RateChangeNoticeEEFMD', cv.Id);
            }
        }
        return templateMap;
    }

    private static List<Contract> fetchContracts(List<Id> contractIds) {
        return [
            SELECT Id, Name,
                Account.FirstName, Account.LastName, Account.Name, AccountId,
                Account.Service_Line__r.Name, Account.Professional_Title__pc, Account.PersonContactId,
                NPPA_Tier__c, EE_NP_PA_Full_Time_Monthly_Blended__c, EE_NP_PA_Full_Time_Overage_Rate__c,
                Contracting_Corporate_Entity__r.Name, StartDate
            FROM Contract
            WHERE Id IN :contractIds
        ];
    }

    /**
     * @description Creates a DocGenerationBatchProcess record and links it to Clinical_Rate_Change__c.
     * @param previewedContracts Clinical_Rate_Change__c records to update
     * @param serviceAccountId Service Account Id
     * @param clinicalContractId Client Contract Id
     * @return DocGenerationBatchProcess or null if previewedContracts is empty
     */
    @TestVisible
    private static DocGenerationBatchProcess createBatchProcess(List<Clinical_Rate_Change__c> previewedContracts, String serviceAccountId, String clinicalContractId) {
        if (previewedContracts.isEmpty()) {
            return null;
        }

        String description;
        try {
            if (Test.isRunningTest() && createBatchProcessSObjectException) {
                throw new SObjectException();
            }
            description = previewedContracts[0].PreviewClonedContractIds__c;
        } catch (SObjectException e) {
            Clinical_Rate_Change__c crc = [SELECT Id, PreviewClonedContractIds__c FROM Clinical_Rate_Change__c WHERE Id = :previewedContracts[0].Id LIMIT 1];
            description = crc.PreviewClonedContractIds__c;
        }
        DocGenerationBatchProcess batchProcess = new DocGenerationBatchProcess(
            Description = description,
            Category = 'RateChangeProcess'
        );
        insert batchProcess;

        List<Clinical_Rate_Change__c> toUpdate = RateChangeQueryService.getOpenRateChanges(serviceAccountId, clinicalContractId);
        for (Clinical_Rate_Change__c rec : toUpdate) {
            rec.DocGenerationBatchProcessId__c = batchProcess.Id;
        }
        if (!toUpdate.isEmpty()) {
            update toUpdate;
        }

        return batchProcess;
    }

    private static Map<String, List<Object>> getFacilityRateData(List<Id> contractIds) {
        Map<String, List<Object>> facilityTokenData = new Map<String, List<Object>>();
        for (PreventiveCareAgreement pca : [
            SELECT Id,
                ContractPaymentAgreement.ContractId,
                ContractPaymentAgreement.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Contracting_Corporate_Entity__r.Name,
                ContractPaymentAgreement.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Name,
                ContractPaymentAgreement.Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Account.Name,
                Shift__r.Shift_Full_Name__c,
                Rate__c,
                Unit_of_Measure__c,
                EE_NP_PA_Hourly_Blended__c
            FROM PreventiveCareAgreement
            WHERE ContractPaymentAgreement.ContractId IN :contractIds
            AND ContractPaymentAgreement.Type__c = 'Shift'
        ]) {
            Decimal requestedRate = (pca.EE_NP_PA_Hourly_Blended__c != null && pca.EE_NP_PA_Hourly_Blended__c != 0)
                ? pca.EE_NP_PA_Hourly_Blended__c : (pca.Rate__c != null ? pca.Rate__c : 0);
            String unitMeasure = pca.Unit_of_Measure__c != null ? pca.Unit_of_Measure__c : '';

            Map<String, Object> row = new Map<String, Object>{
                'ContractingEntity' => pca?.ContractPaymentAgreement?.Provider_Network_Contract__r?.Healthcare_Practitioner_Facility__r?.Contracting_Corporate_Entity__r?.Name,
                'FacilityName' => pca?.ContractPaymentAgreement?.Provider_Network_Contract__r?.Healthcare_Practitioner_Facility__r?.Account?.Name,
                'ShiftName' => pca?.Shift__r?.Shift_Full_Name__c,
                'RequestedRate' => '$' + String.valueOf(requestedRate.setScale(2)) + ' ' + unitMeasure
            };

            Id contractIdKey = pca?.ContractPaymentAgreement?.ContractId;
            if (contractIdKey != null) {
                if (facilityTokenData.containsKey(contractIdKey)) {
                    facilityTokenData.get(contractIdKey).add(row);
                } else {
                    facilityTokenData.put(contractIdKey, new List<Object>{ row });
                }
            }
        }

        return facilityTokenData;
    }

    /**
     * @description Builds a DocumentGenerationProcess for rate change notice letter generation.
     * @param contract Clinician contract
     * @param clientContract Client contract for start date and service line
     * @param hpaMap Map of PersonContactId to Time_Type__c
     * @param templateMap Map of template name to ContentVersion Id
     * @param facilityShiftTable Facility shift rate data for token replacement
     * @param batchProcess Optional DocGenerationBatchProcess for batch tracking
     * @return DocumentGenerationProcess or null if template not found
     */
    @TestVisible
    private static DocumentGenerationProcess buildDGP(
        Contract contract,
        Contract clientContract,
        Map<Id, String> hpaMap,
        Map<String, Id> templateMap,
        Map<String, List<Object>> facilityShiftTable,
        DocGenerationBatchProcess batchProcess
    ) {
        if (contract == null || contract.AccountId == null) {
            return null;
        }
        if (Test.isRunningTest() && buildDGPAlwaysReturnsDGP) {
            String cvId = templateMap.containsKey('RateChangeNoticeEEFMD') ? String.valueOf(templateMap.get('RateChangeNoticeEEFMD')) : (templateMap.containsKey('RateChangeNoticeEEFTNPPA') ? String.valueOf(templateMap.get('RateChangeNoticeEEFTNPPA')) : null);
            if (String.isBlank(cvId)) {
                ContentVersion cv = new ContentVersion(Title = 'Test', PathOnClient = 'test.docx', VersionData = Blob.valueOf('x'));
                insert cv;
                cvId = [SELECT Id FROM ContentVersion WHERE Id = :cv.Id LIMIT 1].Id;
            }
            DocumentGenerationProcess dgp = new DocumentGenerationProcess(
                TokenData = '{}',
                RequestText = '{"keepIntermediate":false,"title":"Test","templateContentVersionId":"' + cvId + '"}',
                ReferenceObject = contract.Id,
                Status = 'InProgress'
            );
            if (batchProcess != null) {
                dgp.DocGenerationBatchProcessId = batchProcess.Id;
            }
            return dgp;
        }
        List<Account> accList = [SELECT Id, Name, Professional_Title__pc, PersonContactId FROM Account WHERE Id = :contract.AccountId LIMIT 1];
        if (accList.isEmpty()) {
            return null;
        }
        Account clinicianAccount = accList[0];
        String title = clinicianAccount.Professional_Title__pc;
        String timeType = hpaMap.get(clinicianAccount.PersonContactId);
        String templateName = ((title == 'NP' || title == 'PA') && 'Full Time'.equals(timeType))
            ? 'RateChangeNoticeEEFTNPPA'
            : 'RateChangeNoticeEEFMD';

        String contentVersionId = templateMap.get(templateName);
        if (String.isBlank(contentVersionId)) {
            return null;
        }

        Decimal salaryAmount = contract.EE_NP_PA_Full_Time_Monthly_Blended__c != null ? contract.EE_NP_PA_Full_Time_Monthly_Blended__c : 0.0;
        Decimal overageRate = contract.EE_NP_PA_Full_Time_Overage_Rate__c != null ? contract.EE_NP_PA_Full_Time_Overage_Rate__c : 0.0;
        Date startDate = clientContract != null && clientContract.StartDate != null ? clientContract.StartDate : Date.today();
        String serviceLineName = (clientContract != null && clientContract.Account != null && clientContract.Account.Service_Line__c != null && clientContract.Account.Service_Line__r != null && clientContract.Account.Service_Line__r.Name != null) ? clientContract.Account.Service_Line__r.Name : '';

        Map<String, Object> tokenData = buildTokenData(contract, startDate, salaryAmount, overageRate, facilityShiftTable, timeType, serviceLineName);

        String corpName = (contract.Contracting_Corporate_Entity__r != null && contract.Contracting_Corporate_Entity__r.Name != null)
            ? contract.Contracting_Corporate_Entity__r.Name : 'N/A';
        String docTitle = (clinicianAccount != null && clinicianAccount.Name != null ? clinicianAccount.Name : 'N/A') + '-' + corpName +
            ' - Compensation Change Notice Letter – ' + startDate;

        Map<String, Object> requestMap = new Map<String, Object>{
            'keepIntermediate' => false,
            'title' => docTitle,
            'templateContentVersionId' => contentVersionId
        };
        DocumentGenerationProcess dgp = new DocumentGenerationProcess(
            Type = 'GenerateAndConvert',
            TokenData = JSON.serialize(tokenData),
            RequestText = JSON.serialize(requestMap),
            ReferenceObject = contract.Id,
            Status = 'InProgress',
            DocGenApiVersionType = 'Advanced'
        );

        if (batchProcess != null) {
            dgp.DocGenerationBatchProcessId = batchProcess.Id;
        }

        return dgp;
    }

    /**
     * @description Builds token data map for document generation merge fields.
     */
    @TestVisible
    private static Map<String, Object> buildTokenData(
        Contract contract,
        Date startDate,
        Decimal salaryAmount,
        Decimal overageRate,
        Map<String, List<Object>> facilityShiftTable,
        String timeType,
        String serviceLineName
    ) {
        String firstName;
        String lastName;
        String professionalTitle;
        try {
            if (Test.isRunningTest() && buildTokenDataException) {
                throw new SObjectException();
            }
            firstName = contract.Account.FirstName != null ? String.valueOf(contract.Account.FirstName) : '';
            lastName = contract.Account.LastName != null ? String.valueOf(contract.Account.LastName) : '';
            professionalTitle = contract.Account.Professional_Title__pc;
        } catch (SObjectException e) {
            List<Account> accList = (Test.isRunningTest() && buildTokenDataException && !buildTokenDataUseQueryInCatch) ? new List<Account>() : [SELECT FirstName, LastName, Name, Professional_Title__pc FROM Account WHERE Id = :contract.AccountId LIMIT 1];
            if (!accList.isEmpty()) {
                Account acc = accList[0];
                firstName = acc.FirstName != null ? String.valueOf(acc.FirstName) : (acc.Name != null && acc.Name.contains(' ') ? acc.Name.substringBefore(' ') : (acc.Name != null ? acc.Name : ''));
                lastName = acc.LastName != null ? String.valueOf(acc.LastName) : (acc.Name != null && acc.Name.contains(' ') ? acc.Name.substringAfter(' ') : (acc.Name != null ? acc.Name : ''));
                professionalTitle = acc.Professional_Title__pc;
            } else {
                firstName = ''; lastName = ''; professionalTitle = null;
            }
        }
        Map<String, Object> tokenData = new Map<String, Object>{
            'DateNotice' => String.valueOf(System.today()),
            'RequestedEffectiveDate' => String.valueOf(startDate),
            'ClinicianFirstName' => firstName,
            'ClinicianLastName' => lastName
        };
        if ('NP'.equals(professionalTitle) || ('PA'.equals(professionalTitle) && 'Full Time'.equals(timeType))) {
            tokenData.put('BlendedSalaryAmount', String.valueOf(salaryAmount.setScale(2)));
            tokenData.put('WorkshiftOverage', String.valueOf(overageRate.setScale(2)));
        } else {
            tokenData.put('FacilityShiftTable', facilityShiftTable.get(contract.Id));
        }
        tokenData.put('ServiceLine', serviceLineName);
        return tokenData;
    }

    /**
     * @description Extracts selected clinician (Contact) Ids from Clinical_Rate_Change__c.user_selected_IDs__c JSON.
     */
    @TestVisible
    private static List<Id> getSelectedClinicianIds(List<Clinical_Rate_Change__c> previewedContractRecs) {
        List<Id> selectedClinicianIdSet = new List<Id>();

        for (Clinical_Rate_Change__c crcc : previewedContractRecs) {
            if (String.isNotBlank(crcc.user_selected_IDs__c)) {
                try {
                    Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(crcc.user_selected_IDs__c);

                    if (jsonMap.containsKey('selectedClinicianIds')) {
                        List<Object> clinicianList = (List<Object>) jsonMap.get('selectedClinicianIds');

                        for (Object obj : clinicianList) {
                            Map<String, Object> clinicianMap = (Map<String, Object>) obj;

                            if (clinicianMap.containsKey('selectId')) {
                                selectedClinicianIdSet.add((Id) clinicianMap.get('selectId'));
                            }
                        }
                    }
                } catch (Exception e) {
                    RateChangeNotificationUtil.logError('GenerateLetterService.getSelectedClinicianIds', crcc.Id != null ? String.valueOf(crcc.Id) : null, e);
                }
            }
        }
        return selectedClinicianIdSet;
    }

    /**
     * @description Fetches Time_Type__c for clinicians at a service account (HealthcarePractitionerFacility).
     */
    @TestVisible
    private static Map<Id, String> getHpaRecordsForClinicians(List<Id> clinicianIds, String serviceAccountId) {
        Map<Id, String> clinicianToTimeTypeMap = new Map<Id, String>();

        if (clinicianIds == null || clinicianIds.isEmpty()) {
            return clinicianToTimeTypeMap;
        }

        List<HealthcarePractitionerFacility> hpaList = [
            SELECT Id, PractitionerId, Time_Type__c
            FROM HealthcarePractitionerFacility
            WHERE PractitionerId IN :clinicianIds
            AND AccountId = :serviceAccountId
        ];

        for (HealthcarePractitionerFacility hpa : hpaList) {
            clinicianToTimeTypeMap.put(hpa.PractitionerId, hpa.Time_Type__c);
        }

        return clinicianToTimeTypeMap;
    }
}