knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Line</label>
    <referenceTo>Service_Line__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/fields/Service_State__c.field-meta.xml
<CustomField>
    <fullName>Service_State__c</fullName>
    <label>Service State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StateGlobalPicklist</valueSetName>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/recordTypes/Service_Account.recordType-meta.xml
<RecordType>
    <fullName>Service_Account</fullName>
    <active>true</active>
    <description>Used to create all Service Lines at a facility, both for Current Opportunities and Future Business</description>
    <label>Service Account</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__ATS_Applicant__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <formula>bpats__Job__r.Facility_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Facility Name</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__ATS_Applicant__c/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <formula>bpats__Job__r.Service_Line2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Line</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/bpats__Job__c.object-meta.xml
<CustomObject>
    <description>Capture information related to a Job Order</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the account</description>
    <inlineHelpText>This is a lookup to the account</inlineHelpText>
    <label>Facility Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Facility Name)</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Facility_Title_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Facility_Title_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the code set object with filters to display active facility type values</description>
    <label>Facility Title</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CodeSet.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CodeSet.CodeSetType</field>
            <operation>equals</operation>
            <value>Facility Title</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/bpats__Job__c/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <description>The type of service line</description>
    <inlineHelpText>The type of service line</inlineHelpText>
    <label>Service Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>Telemedicine</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CodeSet/fields/Code_Set_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Code_Set_Sub_Type__c</fullName>
    <label>Code Set Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CodeSetType</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Leased</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Service_Line__c/Service_Line__c.object-meta.xml
<CustomObject>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/CIFormAssessmentControllerTest.cls
/**
 * This class represents the test class for ClinicianIntakeFormAssessmentController
 * * @author Salesforce Services
 * @version 1.1
 * @since 09/03/2025
 */
@isTest(SeeAllData=false)
private class CIFormAssessmentControllerTest {

    @testSetup
    static void setupTestData() {
        // Get Person Account RecordType
        RecordType personAccountRt = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND IsPersonType = true AND DeveloperName = 'Clinician' LIMIT 1];
        RecordType serviceAccountRt = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Service_Account' LIMIT 1];

        // Create Person Account (Clinician)
        Account personAcct = new Account(
            RecordTypeId = personAccountRt.Id,
            FirstName = 'Test',
            LastName = 'Clinician',
            PersonMailingState = 'California',
            Service_State__c = 'CA',
            Professional_Title__pc = 'DO'
        );
        insert personAcct;

        // Get linked Contact (Person Accounts automatically create a contact)
        Contact con = [SELECT Id FROM Contact WHERE AccountId = :personAcct.Id LIMIT 1];

        // Create CodeSet record (Mapped to Job's Facility_Title_Lookup__c)
        TestDataFactory testDataFactory = new TestDataFactory();
        CodeSet code = testDataFactory.createCodeSet('Employee Title', '21112', 'Facility Title', false);
        code.Code_Set_Sub_Type__c = 'Employee';
        insert code;
        
        
        // Define Service Lines
        List<Service_Line__c> serviceLines = new List<Service_Line__c>{
            new Service_Line__c(Name = 'Virtual Health', Description__c = 'Virtual Health'),
            new Service_Line__c(Name = 'Emergency Medicine', Description__c = 'Emergency Medicine'),
            new Service_Line__c(Name = 'Post Acute Provider Services', Description__c = 'Post Acute Provider Services'),
            new Service_Line__c(Name = 'Critical Care', Description__c = 'Critical Care (formerly ISV)'),
            new Service_Line__c(Name = 'Pediatrics', Description__c = 'Pediatric - Hospital Medicine'),
            new Service_Line__c(Name = 'Urgent Care', Description__c = 'Urgent Care')
        };
        insert serviceLines;

        // Service Accounts and corresponding Jobs
        List<Account> serviceAccounts = new List<Account>();
        for (Service_Line__c sl : serviceLines) {
            serviceAccounts.add(new Account(
                RecordTypeId = serviceAccountRt.Id,
                Name = 'SvcAcct - ' + sl.Name,
                Service_State__c = 'CA',
                Service_Line__c = sl.Id
            ));
        }
        insert serviceAccounts;

        // Create Jobs (traversed by controller logic)
        List<bpats__Job__c> jobList = new List<bpats__Job__c>();
        for (Account svcAcct : serviceAccounts) {
            jobList.add(new bpats__Job__c(
                Facility_Name__c = svcAcct.Id,
                Facility_Title_Lookup__c = code.Id
            ));
        }
        insert jobList;

        List<bpats__ATS_Stage__c> stageList = new List<bpats__ATS_Stage__c>();
        for (bpats__Job__c job : jobList) {
            bpats__ATS_Stage__c stage = new bpats__ATS_Stage__c();
            stage.bpats__Stage_Type__c  = 'Internal Review';
            stage.bpats__Sequence__c  = 1;
            stage.bpats__Job__c = job.Id;
            stageList.add(stage);
        }
        insert stageList;
		
        List<bpats__ATS_Applicant__c> applicantList = new List<bpats__ATS_Applicant__c>();
        for (bpats__ATS_Stage__c stage : stageList) {
            applicantList.add(new bpats__ATS_Applicant__c(
                bpats__ATS_Applicant__c = con.Id,
                bpats__Stage__c = stage.Id,
                bpats__Job__c = stage.bpats__Job__c
            ));
        }
        insert applicantList;
    }

    @isTest
    static void testSetupAssessmentSingleCase() {
        // Arrange
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Case cs = new Case(ContactId = con.Id, Subject = 'Test Case');
        insert cs;

        // Mocking OmniProcesses (Needed for getRelatedOmniscriptIds method)
        List<String> docNames = new List<String>{
            'ClinicianProfileUpdates', 'CCPADoc'
        };

        List<OmniProcess> omniProcesses = new List<OmniProcess>();
        for (String docName : docNames) {
            omniProcesses.add(new OmniProcess(Name = docName, UniqueName = docName, Type = 'Competency',SubType=docName,language='English', IsActive = false));
        }
        insert omniProcesses;

        // Act
        Test.startTest();
        ClinicianIntakeFormAssessmentController.setupAssessment(new List<Case>{cs});
        Test.stopTest();

        // Assert
        List<AssessmentEnvelope> envelopes = [SELECT Id FROM AssessmentEnvelope WHERE RequestReferenceId = :cs.Id];
        System.assertEquals(1, envelopes.size(), 'One Assessment Envelope should be created');
        
        List<AssessmentEnvelopeItem> items = [SELECT Id FROM AssessmentEnvelopeItem WHERE AssessmentEnvelopeId = :envelopes[0].Id];
        System.assert(items.size() > 0, 'Assessment items should have been created');
    }

    @isTest
    static void testExceptionHandling() {
        // Arrange: Create a Case without ContactId to trigger potential error/catch block
        Case cs = new Case(Subject = 'NoContact');
        insert cs;

        // Act
        Test.startTest();
        ClinicianIntakeFormAssessmentController.setupAssessment(new List<Case>{cs});
        Test.stopTest();

        // Assert: The try-catch in controller prevents crash, but no envelope is created
        Integer cnt = [SELECT COUNT() FROM AssessmentEnvelope WHERE RequestReferenceId = :cs.Id];
        System.assertEquals(0, cnt, 'No envelope should be created for invalid case data');
    }
}