knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Client_Change_Management__c/Client_Change_Management__c.object-meta.xml
<CustomObject>
    <label>Client Change Management</label>
    <nameField>
        <displayFormat>CCM-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Change Managements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Client_Change_Management__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Client Change Managements</relationshipLabel>
    <relationshipName>Client_Change_Managements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Client_Change_Management__c/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Practitioner Facility</label>
    <referenceTo>HealthcarePractitionerFacility</referenceTo>
    <relationshipLabel>Client Change Managements</relationshipLabel>
    <relationshipName>Client_Change_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Client_Change_Management__c/fields/Practice_Operation_Change__c.field-meta.xml
<CustomField>
    <fullName>Practice_Operation_Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Operation Change</label>
    <referenceTo>Practice_Operation_Change__c</referenceTo>
    <relationshipLabel>Client Change Managements</relationshipLabel>
    <relationshipName>Client_Change_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Client_Change_Management__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/Clinical_Rate_Change__c.object-meta.xml
<CustomObject>
    <label>Clinical Rate Change</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Clinical Rate Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Rate Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <description>stores the Contract Id of user selected Contract.</description>
    <label>Contract ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/Service_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_ID__c</fullName>
    <description>stores the Id of user selected Facility</description>
    <label>Service Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Clinical_Rate_Change__c/fields/user_selected_IDs__c.field-meta.xml
<CustomField>
    <fullName>user_selected_IDs__c</fullName>
    <description>stores the Ids of Clinicians along with isProcessed attribute in JSON format</description>
    <label>user selected IDs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Interview Cycle</fullName>
            </value>
            <value>
                <fullName>Recruiting</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Practice Operations</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Clinician.recordType-meta.xml
<RecordType>
    <fullName>Clinician</fullName>
    <active>true</active>
    <label>Clinician</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Provider_Network_Contract__r.Healthcare_Practitioner_Facility__c , Provider_Network_Contract__r.Healthcare_Practitioner_Facility__r.Name , &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Healthcare Practitioner Facility</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Facility_Title__c.field-meta.xml
<CustomField>
    <fullName>Facility_Title__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Title</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Healthcare Practitioner Facilities</relationshipLabel>
    <relationshipName>Healthcare_Practitioner_Facilities</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Waiting to be Scheduled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>WTBS Here-WRKG at Sister Site</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Practice_Operation_Change__c/Practice_Operation_Change__c.object-meta.xml
<CustomObject>
    <label>Practice Operation Change</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Operation Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Practice_Operation_Change__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Practice Operation Changes</relationshipLabel>
    <relationshipName>Practice_Operation_Changes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Practice_Operation_Change__c/fields/Facility_Title__c.field-meta.xml
<CustomField>
    <fullName>Facility_Title__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Title</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Practice Operation Changes</relationshipLabel>
    <relationshipName>Practice_Operation_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Practice_Operation_Change__c/fields/Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Type__c</fullName>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Facility_Title__c.field-meta.xml
<CustomField>
    <fullName>Facility_Title__c</fullName>
    <label>Facility Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACES EE Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>ACES EE Physician Assistant</fullName>
            </value>
            <value>
                <fullName>ACES Medical Director</fullName>
            </value>
            <value>
                <fullName>ACES Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>ACES Physician Assistant</fullName>
            </value>
            <value>
                <fullName>ACES Physician EM</fullName>
            </value>
            <value>
                <fullName>ACES Physician PC</fullName>
            </value>
            <value>
                <fullName>Ambassador NP/PA</fullName>
            </value>
            <value>
                <fullName>Ambassador Physician</fullName>
            </value>
            <value>
                <fullName>Assistant Medical Director</fullName>
            </value>
            <value>
                <fullName>EE Assistant System Medical Officer</fullName>
            </value>
            <value>
                <fullName>EE Asst Hospital Med Program Director</fullName>
            </value>
            <value>
                <fullName>EE Hospital Medicine Program Director</fullName>
            </value>
            <value>
                <fullName>EE Lead Midlevel Provider</fullName>
            </value>
            <value>
                <fullName>EE Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>EE Physician</fullName>
            </value>
            <value>
                <fullName>EE Physician Assistant</fullName>
            </value>
            <value>
                <fullName>EE System Medical Officer</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>External Locums</fullName>
            </value>
            <value>
                <fullName>Hospital Medicine Program Administrator</fullName>
            </value>
            <value>
                <fullName>Interim Medical Director</fullName>
            </value>
            <value>
                <fullName>Leased Employee</fullName>
            </value>
            <value>
                <fullName>Leased Medical Director</fullName>
            </value>
            <value>
                <fullName>Medical Director</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Partner Asst Medical Director</fullName>
            </value>
            <value>
                <fullName>Partner Medical Director</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Over_Rate__c.field-meta.xml
<CustomField>
    <fullName>Over_Rate__c</fullName>
    <formula>IF( NOT( Is_Deleted__c ) , IF( Rate__c  &gt; VALUE(Facility_Level_Rate__c), 1, 0) , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Over Rate?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/ClinicalManagerController.cls
/**
 * @description Controller for clinical data management in agent workflows.
 * Provides invocable and AuraEnabled methods for retrieving, processing, and submitting clinical records.
 */
public with sharing class ClinicalManagerController {
    public static String accountId;
    public static String contractId;
    public static String practiceOperationChangeId;

    /** HPF statuses included when querying impacted clinicians */
    private static final Set<String> HPF_STATUSES = new Set<String>{
        'Active',
        'Waiting to be Scheduled',
        'WTBS Here-WRKG at Sister Site'
    };
    /**
     * @description Agentforce invocable method for clinical data management.
     * @param requests List of ClinicalManagerRequest objects.
     * @return List of ClinicalManagerResponse objects.
     */
    @InvocableMethod(
        label='Get Clinical Manager Data' 
        description='Retrieves clinical data for Agentforce with client-side pagination and selection capabilities'
        category='Clinical Management'
    )
    public static List<ClinicalManagerResponse> getClinicalDataForAgentforce(List<ClinicalManagerRequest> requests) {
        List<ClinicalManagerResponse> responses = new List<ClinicalManagerResponse>();
        // String strMessagingSessionId;  // DEAD: assigned but never used
        //for (ClinicalManagerRequest request : requests) {
        ClinicalManagerRequest request = requests[0];
            system.debug('request@@@@'+request);
            try {
                ClinicalManagerResponse response = new ClinicalManagerResponse();
                
                if (!String.isBlank(request.accId)) {
                    accountId = request.accId; 
                }
                
                if (!String.isBlank(request.contractId)) {
                    contractId = request.contractId; 
                } 
                
                if (!String.isBlank(request.practiceOperationChangeId)) {
                    practiceOperationChangeId = request.practiceOperationChangeId; 
                } 
                
                // strMessagingSessionId = request.messagingSessionId;  // DEAD: assigned but never used
                
                // Set default values if not provided
                if (String.isBlank(request.actionType)) {
                    request.actionType = 'GET_DATA';
                }
                
                // Validate accountId for actions that require it
                if (String.isBlank(accountId) && 
                    (request.actionType == 'GET_DATA' || request.actionType == 'GET_ALL_IDS' || request.actionType == 'GET_SUMMARY')) {
                    response.success = false;
                    response.message = 'Account ID is required to retrieve impacted clinicians.';
                    responses.add(response);
                    return responses;
                }
                
                // Handle different action types
                if (request.actionType == 'GET_DATA') {
                    // Get all data (client-side pagination)
                    ClinicalDataWrapper wrapper = getClinicalData();
                    response.success = true;
                    response.message = 'Successfully retrieved ' + wrapper.records.size() + ' impacted clinicians';
                    
                    // Populate the nested structure for Custom Lightning Type
                    response.clinicalDataList = new ClinicalManagerList();
                    response.clinicalDataList.clinicalRecords = wrapper.records;
                    response.clinicalDataList.totalRecords = wrapper.totalRecords;
                    
                    // Keep existing fields for backward compatibility
                    response.totalRecords = wrapper.totalRecords;
                    response.recordsJson = JSON.serialize(wrapper.records);
                    response.clinicalDataList.accId = accountId;
                    response.clinicalDataList.contractId = contractId;
                    
                } else if (request.actionType == 'GET_ALL_IDS') {
                    // Get all record IDs for selection (inline logic)
                    ClinicalDataWrapper wrapper = getClinicalData();
                    List<String> allIds = new List<String>();
                    for (ClinicalRecord record : wrapper.records) {
                        allIds.add(record.id);
                    }
                    response.success = true;
                    response.allRecordIds = allIds;
                    response.message = 'Successfully retrieved ' + allIds.size() + ' impacted clinician IDs';
                    
                } else if (request.actionType == 'GET_SUMMARY') {
                    // Get summary information
                    Integer totalRecords = [SELECT COUNT()
                                            FROM HealthcarePractitionerFacility
                                            WHERE AccountId = :accountId
                                            AND Status__c IN :HPF_STATUSES];
                    response.success = true;
                    response.totalRecords = totalRecords;
                    response.message = 'Total impacted clinicians available: ' + totalRecords;
                    
                } else if (request.actionType == 'SUBMIT_SELECTION') {
                    // Handle submission of selected records
                    response = processSubmittedRecords(request);
                    
                } else {
                    response.success = false;
                    response.message = 'Invalid action type. Supported actions: GET_DATA, GET_ALL_IDS, GET_SUMMARY, SUBMIT_SELECTION';
                }
                responses.add(response);   
            } catch (Exception e) {
                system.debug('Exception==='+e+'===line#===='+ e.getLineNumber());
                system.debug('Exception==='+'===Error message===='+ e.getMessage());
                ClinicalManagerResponse errorResponse = new ClinicalManagerResponse();
                errorResponse.success = false;
                errorResponse.message = 'Error processing request: ' + e.getMessage();
                responses.add(errorResponse);
            }
        //}
        return responses;
    }
    
    /**
     * @description Lightning-compatible method for LWC to call directly.
     * @param actionType Type of action to perform.
     * @param selectedRecordIds List of selected record IDs.
     * @param accountId Account ID for context.
     * @param lContractId Contract ID for context.
     * @param submissionDataJson Optional JSON metadata.
     * @return LightningResponse Lightning-serializable response.
     */
    @AuraEnabled(cacheable=false)
    public static LightningResponse processSelectedRecords(
        String actionType, 
        List<String> selectedRecordIds, 
        String accountId, 
        String lContractId,
        String submissionDataJson
    ) {
        try {
            // Set the static accountId for use in other methods
            ClinicalManagerController.accountId = accountId;
            
            // Create a request object to reuse existing logic
            ClinicalManagerRequest request = new ClinicalManagerRequest();
            request.actionType = actionType;
            request.selectedRecordIds = selectedRecordIds;
            request.accId = accountId;
            request.submissionDataJson = submissionDataJson;
            request.contractId = lContractId;
            // Call the existing processing method and convert to Lightning response
            ClinicalManagerResponse flowResponse = processSubmittedRecords(request);
            
            // Convert to Lightning-compatible response
            LightningResponse lightningResponse = new LightningResponse();
            lightningResponse.success = flowResponse.success;
            lightningResponse.message = flowResponse.message;
            lightningResponse.recordsJson = flowResponse.recordsJson;
            lightningResponse.totalRecords = flowResponse.totalRecords;
            lightningResponse.allRecordIds = flowResponse.allRecordIds;
            
            return lightningResponse;
            
        } catch (Exception e) {
            LightningResponse response = new LightningResponse();response.success = false;response.message = 'Error processing selected records: ' + e.getMessage();
            System.debug('Error in processSelectedRecords: ' + e.getMessage());
            return response;
        }
    }
    
    /**
     * @description Lightning-compatible response class for AuraEnabled methods (no @InvocableVariable annotations).
     */
    public class LightningResponse {
        @AuraEnabled public Boolean success;
        @AuraEnabled public String message;
        @AuraEnabled public String recordsJson;
        @AuraEnabled public List<String> allRecordIds;
        @AuraEnabled public Integer totalRecords;
        /** Default constructor initializing all fields */
        public LightningResponse() {
            this.success = false;
            this.message = '';
            this.recordsJson = '';
            this.allRecordIds = new List<String>();
            this.totalRecords = 0;
            
        }
    }
    
    // DEAD: getClinicalDataForLightning - not called from LWC (data comes from Agentforce via getClinicalDataForAgentforce)
    // /**
    // * @description Lightning-compatible method to get clinical data (bypasses @InvocableMethod issues)
    // * @param accountId Account ID for context
    // * @return LightningResponse containing clinical data
    // */
    // @AuraEnabled(cacheable=false)
    // public static LightningResponse getClinicalDataForLightning(String accountId) {
    //     try {
    //         ClinicalManagerController.accountId = accountId;
    //         ClinicalDataWrapper wrapper = getClinicalData();
    //         LightningResponse response = new LightningResponse();
    //         response.success = true;
    //         response.message = 'Successfully retrieved ' + wrapper.records.size() + ' clinical records';
    //         response.recordsJson = JSON.serialize(wrapper.records);
    //         response.totalRecords = wrapper.totalRecords;
    //         return response;
    //     } catch (Exception e) {
    //         LightningResponse response = new LightningResponse();
    //         response.success = false;
    //         response.message = 'Error retrieving clinical data: ' + e.getMessage();
    //         System.debug('Error in getClinicalDataForLightning: ' + e.getMessage());
    //         return response;
    //     }
    // }
    
    
    
    /**
     * @description Input class for Agentforce invocable method.
     */
    public class ClinicalManagerRequest {
        @InvocableVariable(label='account recId' description='stores id of account selected by user' required=false)
        public String accId;
        @InvocableVariable(label='Contract recId' description='stores id of user selected Contract' required=false)
        public String contractId;
        @InvocableVariable(label='Practice Operation Change recId' description='stores id of user selected practice operation change id' required=true)
        public String practiceOperationChangeId;
        @InvocableVariable(label='Action Type' description='Type of action to perform (GET_DATA, GET_ALL_IDS, GET_SUMMARY, SUBMIT_SELECTION). Default: GET_DATA' required=false)
        public String actionType;
        
        // DEAD: filterCriteria declared but never used in controller logic
        // @InvocableVariable(label='Filter Criteria' description='Optional filter criteria for records' required=false)
        // public String filterCriteria;
        
        @InvocableVariable(label='Selected Record IDs' description='List of selected record IDs for submission' required=false)
        public List<String> selectedRecordIds;
        
        @InvocableVariable(label='Submission Data JSON' description='JSON string containing submission metadata' required=false)
        public String submissionDataJson;
        
        @InvocableVariable(label='Messaging Session Id' required=false)
        public String messagingSessionId;
        
    }
    
    /**
     * @description Output class for Agentforce invocable method.
     */
    public class ClinicalManagerResponse {
        @InvocableVariable(label='Success' description='Whether the operation was successful')
        public Boolean success;
        
        @InvocableVariable(label='Message' description='Response message or error details')
        public String message;
        
        @InvocableVariable(label='Records JSON' description='JSON string containing clinical records')
        public String recordsJson;
        
        @InvocableVariable(label='All Record IDs' description='List of all record IDs for selection')
        public List<String> allRecordIds;
        
        @InvocableVariable(label='Total Records' description='Total number of records available')
        public Integer totalRecords;
        
        @InvocableVariable(label='Selected Clinician IDs' description='Value for selectedClinicianIds context variable')
        public String selectedClinicianIds;
        
        
        @InvocableVariable(label='Clinical Data List' description='Nested clinical data structure for Custom Lightning Types')
        public ClinicalManagerList clinicalDataList;
        
        @InvocableVariable(label='trigger URLs Generation' description='Flag for triggering the \'Get Contract File Links\' method when \'trigger URLs Generation\' is TRUE')
        public Boolean triggerURLGeneration = false;
        
        // DEAD: accId and contractId never set; clinicalDataList.accId/contractId used instead
        // @InvocableVariable(label='account recId' description='stores id of account selected by user' required=false)
        // public String accId;
        //
        // @InvocableVariable(label='Contract recId' description='stores id of user selected Contract' required=false)
        // public String contractId;
    }
    
    /**
     * @description Nested data structure for Custom Lightning Types.
     */
    public class ClinicalManagerList {
        @InvocableVariable(label='Clinical Records' description='List of clinical records')
        public List<ClinicalRecord> clinicalRecords;
        
        @InvocableVariable(label='Total Records' description='Total number of records')
        public Integer totalRecords;
        
        @InvocableVariable(label='Account Id' description='account id')
        public String accId;
        
        @InvocableVariable(label='Contract Id' description='contract id')
        public String contractId;
    }
    
    /**
     * @description Process submitted records from Agentforce.
     * @param request ClinicalManagerRequest containing submission data.
     * @return ClinicalManagerResponse with processing results.
     */
    private static ClinicalManagerResponse processSubmittedRecords(ClinicalManagerRequest request) {
        ClinicalManagerResponse response = new ClinicalManagerResponse();
        List<Id> lstSelectedClinicianIds = new List<Id>();
        try {
            List<String> selectedIds = request.selectedRecordIds;
            
            if (selectedIds == null || selectedIds.isEmpty()) {
                response.success = false;
                response.message = 'No records selected for submission';
                return response;
            }
            
            // Query the selected records
            List<HealthCarePractitionerFacility> selectedRecords = [
                SELECT 
                Id, 
                PractitionerId, 
                Practitioner.Name, 
                Account.Name
                FROM HealthCarePractitionerFacility 
                WHERE Id IN :selectedIds
            ];
            
            // Debug each selected record
            for (Integer i = 0; i < selectedRecords.size(); i++) {
                HealthCarePractitionerFacility record = selectedRecords[i];
                lstSelectedClinicianIds.add(record.PractitionerId);
            }
            
            // Convert List<Id> to List<String>
            List<String> selectedClinicianIdStrings = new List<String>();
            for (Id clinicianId : lstSelectedClinicianIds) {
                selectedClinicianIdStrings.add(clinicianId);
            }
            
            // Create a Map to hold the list under a specific key
            Map<String, List<String>> jsonBody = new Map<String, List<String>>();
            jsonBody.put('selectedClinicianIds', selectedClinicianIdStrings);
            
            // Serialize the map into a JSON string
            String jsonString = JSON.serialize(jsonBody);
            String finalJSON = convertToComplexClinicianFormat(jsonString);            
            jsonString = finalJSON;
            if (String.isNotBlank(jsonString)){
                Clinical_Rate_Change__c crc = RateChangeQueryService.getOpenRateChange(request.accId, request.contractId);
                if (crc == null){
                    Clinical_Rate_Change__c agData = new Clinical_Rate_Change__c();
                    agData.user_selected_Ids__c = jsonString;
                    agData.Service_Account_ID__c = request.accId;
                    agData.Contract_ID__c = request.contractId;
                    agData.Status__c = 'Open';
                    insert agData;
                } else {
                    crc.user_selected_Ids__c = jsonString;
                    update crc;
                }
                response.triggerURLGeneration = true;  
                response.selectedClinicianIds = jsonString;
            }     
            
            // DEAD: submissionDataJson parsed but result never used (only System.debug)
            // if (!String.isBlank(request.submissionDataJson)) {
            //     try {
            //         Map<String, Object> submissionData = (Map<String, Object>)
            //             JSON.deserializeUntyped(request.submissionDataJson);
            //         System.debug('Submission metadata: ' + submissionData);
            //     } catch (Exception jsonError) {
            //         System.debug('Error parsing submission JSON: ' + jsonError.getMessage());
            //     }
            // }
            
            // Successful processing
            response.success = true;
            response.message = 'Successfully processed ' + selectedRecords.size() + ' selected records';
            response.totalRecords = selectedRecords.size();
            
            // Optionally return processed data
            List<ClinicalRecord> processedRecords = new List<ClinicalRecord>();
            for (HealthCarePractitionerFacility record : selectedRecords) {
                ClinicalRecord clinicalRecord = new ClinicalRecord();
                clinicalRecord.id = record.Id;
                clinicalRecord.clinicianName = record.Practitioner.Name;
                clinicalRecord.facilityTitle = record.Account.Name;
                clinicalRecord.overrate = 'Processed'; // Mark as processed
                processedRecords.add(clinicalRecord);
            }
            
            response.recordsJson = JSON.serialize(processedRecords);
            
        } catch (Exception e) {
            System.debug('Error processing submitted records: ' + e.getMessage());
            response.success = false;
            response.message = 'Error processing submission: ' + e.getMessage();
        }
        system.debug('processSubmittedRecords ====Response=====>'+response);
        return response;
    }
    
    /**
     * @description Converts simple selectedClinicianIds JSON to complex format with selectId objects.
     * @param inputJSON JSON string with selectedClinicianIds array
     * @return JSON string with selectedClinicianIds as array of objects with selectId, or null on error
     */
    public static String convertToComplexClinicianFormat(String inputJSON) {
        try {
            // Parse the input JSON
            Map<String, Object> inputObject = (Map<String, Object>) JSON.deserializeUntyped(inputJSON);
            List<Object> selectedIds = (List<Object>) inputObject.get('selectedClinicianIds');
            
            // Bulkified approach - create all records at once
            List<Map<String, Object>> complexClinicianData = new List<Map<String, Object>>();
            
            // Process all IDs in bulk
            for (Object idObj : selectedIds) {
                String selectId = (String) idObj;
                
                Map<String, Object> clinicianRecord = new Map<String, Object>{
                    'selectId' => selectId/*,
                        'isProcessed' => false  // All marked as false*/
                        };
                            
                            complexClinicianData.add(clinicianRecord);
            }
            
            // Create the target JSON object
            Map<String, Object> targetJsonObject = new Map<String, Object>{
                'selectedClinicianIds' => complexClinicianData
                    };
                        
                        // Convert to JSON string and return
                        return JSON.serialize(targetJsonObject);
            
        } catch (Exception e) {
            System.debug('Error converting JSON: ' + e.getMessage());
            return null;
        }
    }
    
    // DEAD: determineProcessedStatus - never called from production code, only from test
    // /**
    //  * @description Determines if a clinician record has been processed (exists in Contact).
    //  * @param selectId Contact/Clinician Id to check
    //  * @return true if record exists, false otherwise
    //  */
    // @TestVisible private static Boolean determineProcessedStatus(String selectId) {
    //     List<Contact> existingContacts = [SELECT Id FROM Contact WHERE Id = :selectId LIMIT 1];
    //     if (!existingContacts.isEmpty()) {
    //         return true;
    //     }
    //     return false;
    // }
    
    /**
     * @description Internal method to retrieve all clinical records for Agentforce.
     * @return ClinicalDataWrapper containing all clinical records.
     */
    private static ClinicalDataWrapper getClinicalData() {
        try {
            // Get HPF IDs from Client_Change_Management__c with Process Type = Agent and Status = New (contractId required)
            if (String.isBlank(contractId)) {
                ClinicalDataWrapper emptyWrapper = new ClinicalDataWrapper();
                emptyWrapper.records = new List<ClinicalRecord>();
                emptyWrapper.totalRecords = 0;
                return emptyWrapper;
            }
            List<Client_Change_Management__c> ccmRecords = [
                SELECT Healthcare_Practitioner_Facility__c
                FROM Client_Change_Management__c
                WHERE Process_Type__c = 'Agent'
                  AND Status__c = 'New'
                  AND Healthcare_Practitioner_Facility__c != null
                  AND Healthcare_Practitioner_Facility__r.AccountId = :accountId
                  AND Contract__c = :contractId
                  AND Practice_Operation_Change__c = :practiceOperationChangeId
            ];
            Set<Id> hpfIds = new Set<Id>();
            for (Client_Change_Management__c ccm : ccmRecords) {
                hpfIds.add(ccm.Healthcare_Practitioner_Facility__c);
            }
            if (hpfIds.isEmpty()) {
                ClinicalDataWrapper emptyWrapper = new ClinicalDataWrapper();
                emptyWrapper.records = new List<ClinicalRecord>();
                emptyWrapper.totalRecords = 0;
                return emptyWrapper;
            }
            List<HealthcarePractitionerFacility> lstHCP = [
                SELECT Id, Practitioner.Id, Practitioner.Name, Account.Name,
                       Facility_Title__c, Facility_Title__r.Name
                FROM HealthcarePractitionerFacility
                WHERE Id IN :hpfIds
                AND Status__c IN :HPF_STATUSES
            ];

            // Get all clinician Ids
            List<Id> lstPractIdsFromHPF = new List<Id>();
            for (HealthcarePractitionerFacility hcp : lstHCP) {
                if(hcp.Practitioner != null && hcp.Practitioner.Id != null) {
                    lstPractIdsFromHPF.add(hcp.Practitioner.Id);
                }
            }

            List<Account> lstClinicianAccIDs = new List<Account>();            
            List<Contract> lstClinicianContracts = new List<Contract>();   
            Map<Id,Integer> mapPersonAccIdVsOverRate = new Map<Id,Integer>();
             
            if (!lstPractIdsFromHPF.isEmpty()) {
                lstClinicianAccIDs = [select id,PersonContactId 
                                      from Account 
                                      WHERE PersonContactId 
                                      IN :lstPractIdsFromHPF limit 100];
            }
            
            // Extract Account IDs for next query
            List<Id> lstAccountIds = new List<Id>();
            for(Account acc : lstClinicianAccIDs) {
                lstAccountIds.add(acc.Id);
            }
            
            if (!lstAccountIds.isEmpty()) {
                lstClinicianContracts = [SELECT Id,Account.Name 
                                         FROM Contract 
                                         where AccountId 
                                         IN: lstAccountIds 
                                         and Status = 'Executed'];
            }
            
            // Extract Contract IDs for next query
            List<Id> lstContractIds = new List<Id>();
            for(Contract con : lstClinicianContracts) {
                lstContractIds.add(con.Id);
            }
            
            if (!lstContractIds.isEmpty()) {
                for (PreventiveCareAgreement pca : [
                    SELECT
                        ContractPaymentAgreement.Contract.Account.PersonContactId
                    FROM PreventiveCareAgreement
                    WHERE ContractPaymentAgreement.ContractId IN :lstContractIds
                    AND Over_Rate__c = 1
                ]) {
                    mapPersonAccIdVsOverRate.put(pca.ContractPaymentAgreement.Contract.Account.PersonContactId, 1);
                }
            }
            // clinician wrapper
            List<ClinicalRecord> clinicalRecords = new List<ClinicalRecord>();
            for (HealthcarePractitionerFacility hcp : lstHCP) {
                ClinicalRecord record = new ClinicalRecord();
                record.id = hcp.Id;
                record.clinicianName = (hcp.Practitioner != null && hcp.Practitioner.Name != null) ? hcp.Practitioner.Name : 'N/A';
                //record.facilityTitle = (hcp.Account != null && hcp.Account.Name != null) ? hcp.Account.Name : 'N/A';
                record.facilityTitle = (hcp.Facility_Title__c != null && hcp.Facility_Title__r.Name != null) ? hcp.Facility_Title__r.Name : 'N/A';
                record.overrate = (hcp.Practitioner != null && mapPersonAccIdVsOverRate.containsKey(hcp.Practitioner.Id)) ? 'Yes' : 'No';                
                clinicalRecords.add(record);
            }

            // Create and return wrapper
            ClinicalDataWrapper wrapper = new ClinicalDataWrapper();
            wrapper.records = clinicalRecords;
            wrapper.totalRecords = clinicalRecords.size();
            return wrapper;
            
        } catch (Exception e) {
            System.debug('Error in getClinicalData: ' + e.getMessage());
            throw new AuraHandledException('Error retrieving impacted clinicians: ' + e.getMessage());
        }
    }
    
    /**
     * @description Internal wrapper class for clinical data retrieval results.
     */
    private class ClinicalDataWrapper {
        /** List of clinical records */
        public List<ClinicalRecord> records { get; set; }
        /** Total record count for pagination */
        public Integer totalRecords { get; set; }
    }
    
    
    /**
     * @description Clinical record data structure for agent workflows.
     */
    public class ClinicalRecord {
        /** Record ID (HealthCarePractitionerFacility Id) */
        @AuraEnabled public String id { get; set; }
        /** Clinician name from Practitioner */
        @AuraEnabled public String clinicianName { get; set; }
        /** Facility title from Facility_Title__r */
        @AuraEnabled public String facilityTitle { get; set; }
        /** Overrate indicator (Yes/No) */
        @AuraEnabled public String overrate { get; set; }
    }
    
}