knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Case/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Practitioner Facility</label>
    <referenceTo>HealthcarePractitionerFacility</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Case/recordTypes/Collaborative_Practice_Agreement.recordType-meta.xml
<RecordType>
    <fullName>Collaborative_Practice_Agreement</fullName>
    <active>true</active>
    <businessProcess>Clinician Onboarding Support Process</businessProcess>
    <label>Collaborative Practice Agreement</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Support Case Process</businessProcess>
    <label>Support</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CodeSet/fields/Code_Set_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Code_Set_Sub_Type__c</fullName>
    <label>Code Set Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CodeSetType</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Leased</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CodeSet/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Leased</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Collaborative_Practice_Agreement__c/Collaborative_Practice_Agreement__c.object-meta.xml
<CustomObject>
    <label>Collaborative Practice Agreement</label>
    <nameField>
        <displayFormat>CPA-{00000}</displayFormat>
        <label>Collaborative Practice Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborative Practice Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Collaborative_Practice_Agreement__c/fields/NP_PA_Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>NP_PA_Healthcare_Practitioner_Facility__c</fullName>
    <label>NP/PA Healthcare Practitioner Facility</label>
    <referenceTo>HealthcarePractitionerFacility</referenceTo>
    <relationshipLabel>Collaborative Practice Agreements</relationshipLabel>
    <relationshipName>Collaborative_Practice_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Collaborative_Practice_Agreement__c/fields/Physician_Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Physician_Healthcare_Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Physician Healthcare Facility</label>
    <referenceTo>HealthcarePractitionerFacility</referenceTo>
    <relationshipLabel>Collaborative Practice Agreements</relationshipLabel>
    <relationshipName>Collaborative_Practice_Agreements1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Collaborative_Practice_Agreement__c/fields/Supervision_Collaboration_Status__c.field-meta.xml
<CustomField>
    <fullName>Supervision_Collaboration_Status__c</fullName>
    <label>Supervision/Collaboration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Superv Phys/INA@ this account</fullName>
            </value>
            <value>
                <fullName>Clinician is Unresponsive</fullName>
            </value>
            <value>
                <fullName>Compliant</fullName>
            </value>
            <value>
                <fullName>Compliant, Supervisor Threshold Met</fullName>
            </value>
            <value>
                <fullName>Compliant – Not Working</fullName>
            </value>
            <value>
                <fullName>Compliant – Upcoming Account Termination</fullName>
            </value>
            <value>
                <fullName>Compliant – Upcoming Physician Termination</fullName>
            </value>
            <value>
                <fullName>Inactivation (delink) Pending</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Compliant</fullName>
            </value>
            <value>
                <fullName>Not Compliant – Not Working</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Not Required Immediately</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Supervising Phys #</fullName>
            </value>
            <value>
                <fullName>Pending with Alternate/Backup Physician</fullName>
            </value>
            <value>
                <fullName>Pending with Medical Board</fullName>
            </value>
            <value>
                <fullName>Pending with Notary Public</fullName>
            </value>
            <value>
                <fullName>Pending with NP/PA</fullName>
            </value>
            <value>
                <fullName>Pending with Nursing Board</fullName>
            </value>
            <value>
                <fullName>Pending with SG for board submission</fullName>
            </value>
            <value>
                <fullName>Pending with Superv/Collab Physician</fullName>
            </value>
            <value>
                <fullName>Physician as Midlevel-Not supervising</fullName>
            </value>
            <value>
                <fullName>Physician Not Eligible to Supervise</fullName>
            </value>
            <value>
                <fullName>Refuses to Supervise/Collaborate</fullName>
            </value>
            <value>
                <fullName>Temporarily Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contact/fields/Professional_Title__c.field-meta.xml
<CustomField>
    <fullName>Professional_Title__c</fullName>
    <label>Professional Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Professional_Title</valueSetName>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Interview Cycle</fullName>
            </value>
            <value>
                <fullName>Recruiting</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Collaborative_Practice_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Collaborative_Practice_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaborative Practice Agreement</label>
    <referenceTo>Collaborative_Practice_Agreement__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Contracting_Corporate_Entity__c.field-meta.xml
<CustomField>
    <fullName>Contracting_Corporate_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Corporate Entity on the Clinician’s Contract</inlineHelpText>
    <label>Contracting Corporate Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeName__c</field>
            <operation>equals</operation>
            <value>Corporate_Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Contracting Corporate Entity)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Leased</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Clinician.recordType-meta.xml
<RecordType>
    <fullName>Clinician</fullName>
    <active>true</active>
    <label>Clinician</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Collaborative_Practice_Agreement.recordType-meta.xml
<RecordType>
    <fullName>Collaborative_Practice_Agreement</fullName>
    <active>true</active>
    <label>Collaborative Practice Agreement</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CPA_Review__c/CPA_Review__c.object-meta.xml
<CustomObject>
    <label>CPA Review</label>
    <nameField>
        <displayFormat>CPA Review-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CPA_Review__c/fields/Collaborative_Practice_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Collaborative_Practice_Agreement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Collaborative Practice Agreement</label>
    <referenceTo>Collaborative_Practice_Agreement__c</referenceTo>
    <relationshipLabel>CPA Reviews</relationshipLabel>
    <relationshipName>CPA_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Contracting_Corporate_Entity__c.field-meta.xml
<CustomField>
    <fullName>Contracting_Corporate_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contracting Corporate Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeName__c</field>
            <operation>equals</operation>
            <value>Corporate_Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcare Practitioner Facilities</relationshipLabel>
    <relationshipName>Healthcare_Practitioner_Facilities</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <formula>TEXT(Facility_Title__r.Code_Set_Sub_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employment Type</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Facility_Title__c.field-meta.xml
<CustomField>
    <fullName>Facility_Title__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Title</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Healthcare Practitioner Facilities</relationshipLabel>
    <relationshipName>Healthcare_Practitioner_Facilities</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/HealthcarePractitionerFacility/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Waiting to be Scheduled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>WTBS Here-WRKG at Sister Site</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ProviderNetworkContract/fields/Healthcare_Practitioner_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Practitioner_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Practitioner Facility</label>
    <referenceTo>HealthcarePractitionerFacility</referenceTo>
    <relationshipLabel>Provider Network Contracts</relationshipLabel>
    <relationshipName>Provider_Network_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/globalValueSets/Professional_Title.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DO</fullName>
    </customValue>
    <customValue>
        <fullName>LPN</fullName>
    </customValue>
    <customValue>
        <fullName>NP</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <customValue>
        <fullName>RN</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>BSN</fullName>
        <isActive>false</isActive>
        <label>BSN</label>
    </customValue>
    <customValue>
        <fullName>PhD</fullName>
        <isActive>false</isActive>
        <label>PhD</label>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
        <isActive>false</isActive>
        <label>CNS</label>
    </customValue>
    <customValue>
        <fullName>CAA</fullName>
        <isActive>false</isActive>
        <label>CAA</label>
    </customValue>
    <customValue>
        <fullName>CRNA</fullName>
        <isActive>false</isActive>
        <label>CRNA</label>
    </customValue>
    <customValue>
        <fullName>LSW</fullName>
        <isActive>false</isActive>
        <label>LSW</label>
    </customValue>
    <customValue>
        <fullName>MSW</fullName>
        <isActive>false</isActive>
        <label>MSW</label>
    </customValue>
    <masterLabel>Professional Title</masterLabel>
</GlobalValueSet>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/CPARelationshipRecordsGeneratorTest.cls
@IsTest
private class CPARelationshipRecordsGeneratorTest {
    
    private static final String PROFILE_NAME = 'Corporate Support';  
    private static final String PERMISSION_SET_GROUP_DEVNAME = 'IT';
    private static final String TEST_USER_EMAIL = 'recruiter@scp.com.invalid';

    @TestSetup
    static void setupTestData() {
        // --- 1. Account Record Types ---
        Id clinicianRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Clinician').getRecordTypeId();
        Id corporateEntityRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Corporate_Entity').getRecordTypeId();
        Id serviceAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Service_Account').getRecordTypeId();
        Id cpaCaseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Collaborative_Practice_Agreement').getRecordTypeId();
        Id clinicianContractRTId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Clinician').getRecordTypeId();
        
        // --- 2. Create Accounts ---
        
        Account clinicianMD = new Account(LastName = 'Test MD Clinician', RecordTypeId = clinicianRTId);
        Account clinicianNP = new Account( LastName = 'Test NP Clinician',RecordTypeId = clinicianRTId);
        Account corporateEntity = new Account(Name  = 'Test Corporate Entity', RecordTypeId = corporateEntityRTId);
        Account serviceAccount = new Account(Name = 'Test Service Account', RecordTypeId = serviceAccountRTId);
        insert new List<Account>{clinicianMD, clinicianNP, corporateEntity, serviceAccount};
            
            // --- 3. Get the Contact IDs which are the same as the Person Account IDs
            Contact physicianContact = [SELECT Id, Professional_Title__c FROM Contact WHERE AccountId = :clinicianMD.Id];
        physicianContact.Professional_Title__c = 'MD';
        Contact npaContact = [SELECT Id, Professional_Title__c FROM Contact WHERE AccountId = :clinicianNP.Id];
        npaContact.Professional_Title__c = 'NP';
        update new List<Contact>{physicianContact, npaContact};
            
            // --- 4. Create Healthcare Payer Network ---
            HealthcarePayerNetwork healthcarePayerNetwork = new HealthcarePayerNetwork(
                Name = 'Test Payer Network',
                PayerId = corporateEntity.Id
            );
        insert healthcarePayerNetwork;

        
        
        // --- 7. Create Code Set Record ---
        CodeSet codeSet = new CodeSet(
            Name = 'Ambassador NP/PA',
            CodeSetType = 'Facility Title',
            StartDate = Date.today().addDays(-2),
            Code_Set_Sub_Type__c = 'Employee',
            Enddate = Date.today().addDays(2),
            code = 'Ambassador NP/PA'
        );
        insert codeSet;
        
        
        // --- 8. Create Healthcare Practitioner Facility (HPF) Records ---
        HealthcarePractitionerFacility physicianHPF = new HealthcarePractitionerFacility(
            Name = 'Physician HPF',
            PractitionerId = physicianContact.Id, // PractitionerId links to HealthcarePractitioner
            AccountId = serviceAccount.Id,
            //Facility_Title__c = codeSet.Id,
            Status__c = 'Prospect',
            Contracting_Corporate_Entity__c = corporateEntity.Id
        );
        HealthcarePractitionerFacility npaHPF = new HealthcarePractitionerFacility(
            Name = 'NP HPF',
            PractitionerId = npaContact.Id,
            AccountId = serviceAccount.Id,
            //Facility_Title__c = codeSet.Id,
            Status__c = 'Prospect',
            Contracting_Corporate_Entity__c = corporateEntity.Id
        );
        insert new List<HealthcarePractitionerFacility>{physicianHPF, npaHPF};
            
            // --- 9. Create Healthcare Provider records and link to Contacts ---
            HealthcareProvider physicianProvider = new HealthcareProvider(
                Name = 'Physician Provider',
                PractitionerId = physicianContact.Id
            );
        HealthcareProvider npaProvider = new HealthcareProvider(
            Name = 'NPA Provider',
            PractitionerId = npaContact.Id
        );
        insert new List<HealthcareProvider>{physicianProvider, npaProvider};
            
            // --- 10. Create Contracts ---
            Contract physicianContract = new Contract(
                AccountId = clinicianMD.Id,
                Status = 'Draft', // Will be updated to Executed in test method
                RecordTypeId = clinicianContractRTId,
                Employment_Type__c = 'Employee'
            );
        Contract npaContract = new Contract(
            AccountId = clinicianNP.Id,
            Status = 'Draft', // Will be updated to Executed in test method
            RecordTypeId = clinicianContractRTId,
            Employment_Type__c = 'Employee'
        );
        insert new List<Contract>{physicianContract, npaContract};
            
            
            // --- 11. Create Provider Network Contracts (PNC) ---
            ProviderNetworkContract physicianPNC = new ProviderNetworkContract(
                Healthcare_Practitioner_Facility__c = physicianHPF.Id,
                ContractId = physicianContract.Id,
                HealthcarePayerNetworkId = healthcarePayerNetwork.Id,
                HealthcareProviderId = physicianProvider.Id,           // Required Field
                StartDate = Date.today(),                              // Required Field
                EndDate = Date.today().addYears(1)   
            );
        ProviderNetworkContract npaPNC = new ProviderNetworkContract(
            Healthcare_Practitioner_Facility__c = npaHPF.Id,
            ContractId = npaContract.Id,
            HealthcarePayerNetworkId = healthcarePayerNetwork.Id,
            HealthcareProviderId = npaProvider.Id,           // Required Field
            StartDate = Date.today(),                              // Required Field
            EndDate = Date.today().addYears(1)   
        );
        insert new List<ProviderNetworkContract>{physicianPNC, npaPNC};
            
         Profile p = [SELECT Id FROM Profile WHERE Name= :PROFILE_NAME]; 
        
        PermissionSetGroup psg = [SELECT Id, Status FROM PermissionSetGroup WHERE DeveloperName = :PERMISSION_SET_GROUP_DEVNAME];
        if (psg.Status != 'Updated') {
            Test.calculatePermissionSetGroup(psg.Id);
        }
        
        System.runAs(new User(Id = Userinfo.getUserId())) {
            User usr = new User(Alias = 'standt', Email= TEST_USER_EMAIL, 
                EmailEncodingKey='UTF-8', LastName='SCPTestUsuer', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName='scptestclassusername2025@scp.com');
            insert usr;

            PermissionSetAssignment psgAssignment = new PermissionSetAssignment(
            AssigneeId = usr.Id,
            PermissionSetGroupId = psg.Id);
            insert psgAssignment;

             // --- 6. Create Account Team Member to set Case Owner ---
            
            AccountTeamMember atm = new AccountTeamMember(
                AccountId = serviceAccount.Id,
                UserId = usr.Id,
                TeamMemberRole = 'Medical Staff Liaison - CPA'
            );
        insert atm;
        }
    }
    
    @IsTest
    static void testCPAAndCaseGenerationForMDDO() {
        User u = [SELECT id from user where email = :TEST_USER_EMAIL LIMIT 1];
        System.runAs(u) {
            // Find the record type IDs for assertions
        Id cpaCaseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Collaborative_Practice_Agreement').getRecordTypeId();
        
        // Query the contracts that were created in @TestSetup
        List<Contract> contracts = [
            SELECT Id, Status FROM Contract 
            WHERE RecordType.DeveloperName = 'Clinician' and Status = 'Draft'
        ];
        
        
        // Ensure there are contracts to test
        System.assertNotEquals(0, contracts.size(), 'Contracts should have been created in @TestSetup.');
        
        // Change the status of contracts to 'Executed' to trigger the process
        for(Contract c : contracts) {
            c.Status = 'Executed';
        }
        update contracts;
    
        Test.startTest();
        // Call the invocable method with the contract IDs
        CPARelationshipRecordsGenerator.startCPAProcessing(new List<Id>{contracts[0].Id});
        Test.stopTest();
        
        // Assertions
        List<Collaborative_Practice_Agreement__c> cpas = [
            SELECT Id, Physician_Healthcare_Facility__c, Physician_Healthcare_Facility__r.PractitionerId, 
                   NP_PA_Healthcare_Practitioner_Facility__c, Supervision_Collaboration_Status__c 
            FROM Collaborative_Practice_Agreement__c
        ];
      
        
        CPAReviewCaseGenerator secondClass = new CPAReviewCaseGenerator(cpas, cpas[0].Physician_Healthcare_Facility__r.PractitionerId);
        secondClass.execute(null);
        
        // Assert that a CPA record was created for each clinician
        System.assertEquals(1, cpas.size(), 'One CPA records should have been created.');
        
        // Assert that a Case and CPA Review record were created
        List<Case> cpaCases = [SELECT Id FROM Case WHERE RecordTypeId = :cpaCaseRTId];
        System.assertEquals(1, cpaCases.size(), 'A single Case record should have been created for the facility.');
        
        Case cpaCase = cpaCases[0];
        
        List<CPA_Review__c> cpaReviews = [SELECT Id, Collaborative_Practice_Agreement__c, Case__c FROM CPA_Review__c WHERE Case__c = :cpaCase.Id];
        System.assertEquals(1, cpaReviews.size(), 'One CPA Review records should have been created.');
        
        // Verify the links between the CPA Reviews and the CPAs
        Set<Id> cpaIdsFromReviews = new Set<Id>();
        for (CPA_Review__c review : cpaReviews) {
            cpaIdsFromReviews.add(review.Collaborative_Practice_Agreement__c);
        }
        
        Set<Id> originalCpaIds = new Set<Id>();
        for (Collaborative_Practice_Agreement__c cpa : cpas) {
            originalCpaIds.add(cpa.Id);
        }
        System.assertEquals(originalCpaIds, cpaIdsFromReviews, 'All created CPA Ids should be linked to the new CPA Review records.');
        }
        
    }
    @IsTest
    static void testCPAAndCaseGenerationForNpPA() {
        User u = [SELECT id from user where email = :TEST_USER_EMAIL LIMIT 1];
        System.runAs(u) {
        // Find the record type IDs for assertions
        Id cpaCaseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Collaborative_Practice_Agreement').getRecordTypeId();
        
        // Query the contracts that were created in @TestSetup
        List<Contract> contracts = [
            SELECT Id, Status FROM Contract 
            WHERE RecordType.DeveloperName = 'Clinician' and Status = 'Draft'
        ];
        
       
        
        // Ensure there are contracts to test
        System.assertNotEquals(0, contracts.size(), 'Contracts should have been created in @TestSetup.');
        
        // Change the status of contracts to 'Executed' to trigger the process
        for(Contract c : contracts) {
            c.Status = 'Executed';
        }
        update contracts;
        
        Test.startTest();
        // Call the invocable method with the contract IDs
        CPARelationshipRecordsGenerator.startCPAProcessing(new List<Id>{contracts[1].Id});
        Test.stopTest();
        
        // Assertions
        List<Collaborative_Practice_Agreement__c> cpas = [
            SELECT Id, Physician_Healthcare_Facility__c, Physician_Healthcare_Facility__r.PractitionerId, 
                   NP_PA_Healthcare_Practitioner_Facility__c, Supervision_Collaboration_Status__c 
            FROM Collaborative_Practice_Agreement__c
        ];
              
        
        CPAReviewCaseGenerator secondClass = new CPAReviewCaseGenerator(cpas, cpas[0].Physician_Healthcare_Facility__r.PractitionerId);
        
        secondClass.execute(null);
        
        
        // Assert that a CPA record was created for each clinician
        System.assertEquals(1, cpas.size(), 'One CPA records should have been created.');
        
        // Assert that a Case and CPA Review record were created
        List<Case> cpaCases = [SELECT Id FROM Case WHERE RecordTypeId = :cpaCaseRTId];
        System.assertEquals(1, cpaCases.size(), 'A single Case record should have been created for the facility.');
        
        Case cpaCase = cpaCases[0];
        
        List<CPA_Review__c> cpaReviews = [SELECT Id, Collaborative_Practice_Agreement__c, Case__c FROM CPA_Review__c WHERE Case__c = :cpaCase.Id];
        System.assertEquals(1, cpaReviews.size(), 'One CPA Review records should have been created.');
        
        // Verify the links between the CPA Reviews and the CPAs
        Set<Id> cpaIdsFromReviews = new Set<Id>();
        for (CPA_Review__c review : cpaReviews) {
            cpaIdsFromReviews.add(review.Collaborative_Practice_Agreement__c);
        }
        
        Set<Id> originalCpaIds = new Set<Id>();
        for (Collaborative_Practice_Agreement__c cpa : cpas) {
            originalCpaIds.add(cpa.Id);
        }
        System.assertEquals(originalCpaIds, cpaIdsFromReviews, 'All created CPA Ids should be linked to the new CPA Review records.');
        }
    }
    
    @IsTest
    static void testUpdateExistingCPA() {
        User u = [SELECT id from user where email = :TEST_USER_EMAIL LIMIT 1];
        System.runAs(u) {
        Id cpaCaseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Collaborative_Practice_Agreement').getRecordTypeId();
        Id clinicianContractRTId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Clinician').getRecordTypeId();
        Account clinicianMD = [SELECT Id FROM Account WHERE LastName = 'Test MD Clinician' LIMIT 1];
        Account clinicianNP = [SELECT Id FROM Account WHERE LastName = 'Test NP Clinician' LIMIT 1];
        HealthcarePractitionerFacility physicianHPF = [SELECT Id,PractitionerId,AccountId,Status__c,Contracting_Corporate_Entity__c FROM HealthcarePractitionerFacility WHERE PractitionerId IN (SELECT Id FROM Contact WHERE AccountId = :clinicianMD.Id)];
        HealthcarePractitionerFacility npaHPF = [SELECT Id,PractitionerId FROM HealthcarePractitionerFacility WHERE PractitionerId IN (SELECT Id FROM Contact WHERE AccountId = :clinicianNP.Id)];
        
        // Manually create an existing CPA record
        Collaborative_Practice_Agreement__c existingCpa = new Collaborative_Practice_Agreement__c(
            Physician_Healthcare_Facility__c = physicianHPF.Id,
            NP_PA_Healthcare_Practitioner_Facility__c = npaHPF.Id,
            Supervision_Collaboration_Status__c = 'Pending'

        );
        insert existingCpa;
        
        physicianHPF.Status__c = 'Active';
        update physicianHPF;
        HealthcarePractitionerFacility physicianHPFNew = new HealthcarePractitionerFacility(
            Name = 'Physician HPF New',
            PractitionerId = physicianHPF.PractitionerId, // PractitionerId links to HealthcarePractitioner
            AccountId = physicianHPF.AccountId,
            //Facility_Title__c = codeSet.Id,
            Status__c = 'Prospect',
            Contracting_Corporate_Entity__c = physicianHPF.Contracting_Corporate_Entity__c
        );
        
        insert physicianHPFNew;
        
        Contract phyContract = [SELECT Id, Status FROM Contract WHERE AccountId = :clinicianMD.Id];
        
        Contract physicianContractNew = new Contract(
            AccountId = clinicianMD.Id,
            Status = 'Draft', // Will be updated to Executed in test method
            RecordTypeId = clinicianContractRTId,
            Employment_Type__c = 'Employee',
            StartDate = System.today() + 10
        );
        insert physicianContractNew;
        
        phyContract.Status = 'Canceled';
        update phyContract;
        
       
        ProviderNetworkContract physicianPNCNew = new ProviderNetworkContract(
            Healthcare_Practitioner_Facility__c = physicianHPFNew.Id,
            ContractId = physicianContractNew.Id,
            HealthcarePayerNetworkId = [SELECT Id FROM HealthcarePayerNetwork LIMIT 1].Id,
            HealthcareProviderId = [SELECT Id FROM HealthcareProvider WHERE PractitionerId = :[SELECT Id FROM Contact WHERE AccountId = :clinicianMD.Id limit 1].Id LIMIT 1].Id,
            StartDate = Date.today() + 11,                              // Required Field
            EndDate = Date.today().addYears(1)   
        );
        
        insert physicianPNCNew ;
        
        // Simulate a contract update for the NP
        Contract phyContractNew = [SELECT Id, Status FROM Contract WHERE AccountId = :clinicianMD.Id and status = 'Draft'];
        phyContractNew.Status = 'Executed';
        
        
        Test.startTest();
            update phyContractNew;
            CPARelationshipRecordsGenerator.startCPAProcessing(new List<Id>{phyContractNew.Id});
        Test.stopTest();
        
        List<Collaborative_Practice_Agreement__c> cpas = [
            SELECT Id, Supervision_Collaboration_Status__c ,Physician_Healthcare_Facility__r.PractitionerId,Physician_Healthcare_Facility__c,
                   NP_PA_Healthcare_Practitioner_Facility__c
            FROM Collaborative_Practice_Agreement__c 
            WHERE Id = :existingCpa.Id
        ];
       
        // Pass the updated CPA IDs for update scenario
        Set<Id> updatedCPAIds = new Set<Id>{existingCpa.Id};
        CPAReviewCaseGenerator secondClass = new CPAReviewCaseGenerator(cpas, cpas[0].Physician_Healthcare_Facility__r.PractitionerId, updatedCPAIds);
        secondClass.execute(null);
        
        System.assertEquals(1, cpas.size(), 'The existing CPA record should have been found.');
        System.assertEquals('Pending', cpas[0].Supervision_Collaboration_Status__c, 'The existing CPA record should have been updated to Pending.');
        
        List<Case> cpaCases = [SELECT Id FROM Case WHERE RecordTypeId = :cpaCaseRTId];
        System.assertEquals(1, cpaCases.size(), 'A new Case should be created for the updated CPA.');
        }
    }
    
    
    @IsTest
    static void testEmptyContractIds() {
        User u = [SELECT id from user where email = :TEST_USER_EMAIL LIMIT 1];
        System.runAs(u) {
        Test.startTest();
        CPARelationshipRecordsGenerator.startCPAProcessing(new List<Id>());
        CPARelationshipRecordsGenerator.startCPAProcessing(null);
        Test.stopTest();
        
        // Assert that no new records were created
        System.assertEquals(0, [SELECT count() FROM Collaborative_Practice_Agreement__c], 'No CPA records should have been created for null or empty list.');
        System.assertEquals(0, [SELECT count() FROM Case WHERE RecordType.DeveloperName = 'Collaborative_Practice_Agreement'], 'No Case records should have been created.');
    
        }
    }
}