knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CapturePCA__e/CapturePCA__e.object-meta.xml
<CustomObject>
    <label>CapturePCA</label>
    <pluralLabel>CapturePCAs</pluralLabel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CapturePCA__e/fields/contractId__c.field-meta.xml
<CustomField>
    <fullName>contractId__c</fullName>
    <label>contractId</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CapturePCA__e/fields/CPAId__c.field-meta.xml
<CustomField>
    <fullName>CPAId__c</fullName>
    <label>CPAId</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CapturePCA__e/fields/PCAId__c.field-meta.xml
<CustomField>
    <fullName>PCAId__c</fullName>
    <label>PCAId</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/contractId__c.field-meta.xml
<CustomField>
    <fullName>contractId__c</fullName>
    <formula>ContractPaymentAgreement.ContractId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>contractId</label>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>per Metric</fullName>
            </value>
            <value>
                <fullName>% Salary Reduction</fullName>
            </value>
            <value>
                <fullName>per Monthly Tier</fullName>
            </value>
            <value>
                <fullName>per Hour</fullName>
            </value>
            <value>
                <fullName>per Shift</fullName>
            </value>
            <value>
                <fullName>per Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/PCATriggerHandler.cls
public class PCATriggerHandler {
    
    public Static void createPlatformEvt(List<PreventiveCareAgreement> pcaList) {
        List<CapturePCA__e> peList = new List <CapturePCA__e>();
        
        
        for (PreventiveCareAgreement pca : pcaList) {
            CapturePCA__e pe = new CapturePCA__e();
            if (pca.Rate__c != null && pca.Unit_of_Measure__c == 'per Hour') {
                pe.CPAId__c = pca.contractId__c ;
                pe.PCAId__c = pca.Id;
                peList.add(pe);
            }
        }
        // Publish the events
        
        Database.SaveResult[] srList = EventBus.publish(peList);
        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully inserted : ' + sr.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {                   
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                }
            }
            
        }
    }
    
    
}