knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Account/recordTypes/Service_Account.recordType-meta.xml
<RecordType>
    <fullName>Service_Account</fullName>
    <active>true</active>
    <description>Used to create all Service Lines at a facility, both for Current Opportunities and Future Business</description>
    <label>Service Account</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CodeSet/fields/Shift_Day_of_the_Week__c.field-meta.xml
<CustomField>
    <fullName>Shift_Day_of_the_Week__c</fullName>
    <label>Shift Day of the Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CodeSet/fields/Shift_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Shift_End_Time__c</fullName>
    <label>Shift End Time</label>
    <type>Time</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/CodeSet/fields/Shift_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Shift_Start_Time__c</fullName>
    <label>Shift Start Time</label>
    <type>Time</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>%/Rate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stipend</fullName>
            </value>
            <value>
                <fullName>Shift</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Leadership Incentives</fullName>
            </value>
            <value>
                <fullName>Locums</fullName>
                <isActive>false</isActive>
                <label>Locums</label>
            </value>
            <value>
                <fullName>Locums On Call</fullName>
                <isActive>false</isActive>
                <label>Locums On Call</label>
            </value>
            <value>
                <fullName>Locums Travel</fullName>
                <isActive>false</isActive>
                <label>Locums Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/FacilityTitle__c.field-meta.xml
<CustomField>
    <fullName>FacilityTitle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Title</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>CodeSet.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CodeSet.CodeSetType</field>
            <operation>equals</operation>
            <value>Facility Title</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Preventive Care Agreements (Facility Title)</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements1</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Shift__c.field-meta.xml
<CustomField>
    <fullName>Shift__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shift</label>
    <referenceTo>Shift__c</referenceTo>
    <relationshipLabel>Preventive Care Agreements</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Shift_Iteration__c.field-meta.xml
<CustomField>
    <fullName>Shift_Iteration__c</fullName>
    <label>Shift Iteration</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Preventive Care Agreements (Type)</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements2</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/Shift__c.object-meta.xml
<CustomObject>
    <label>Shift</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Shift Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_Day_of_the_Week__c.field-meta.xml
<CustomField>
    <fullName>Shift_Day_of_the_Week__c</fullName>
    <label>Shift Day of the Week</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Shift_End_Time__c</fullName>
    <label>Shift End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_Iteration__c.field-meta.xml
<CustomField>
    <fullName>Shift_Iteration__c</fullName>
    <label>Shift Iteration</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_Name__c.field-meta.xml
<CustomField>
    <fullName>Shift_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shift Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CodeSet.CodeSetType</field>
            <operation>equals</operation>
            <value>Shift</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Shift_Start_Time__c</fullName>
    <label>Shift Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NP/PA</fullName>
            </value>
            <value>
                <fullName>MD/DO</fullName>
            </value>
            <value>
                <fullName>RN/LPN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/CheckRatesForServiceAccFacility_Test.cls
@Istest(SeeAllData=false)
public class CheckRatesForServiceAccFacility_Test {
    @testSetup
	static void setupTestData() {
 TestDataFactoryCore TDF = new TestDataFactoryCore();

        // Accounts and Contacts
        Account acc = TDF.createServiceAccount('Test Service Account', null, 'Service_Account', true);
        Contact con = TDF.createContact('Test Contact', acc, true);

        // Contract setup
        Contract contract = new Contract(
            AccountId = acc.Id,
            StartDate = Date.today(),
            EndDate = Date.today().addMonths(12),
            Status = 'Draft'
        );
        insert contract;

        // Facility Title
        CodeSet facilityCode = new CodeSet(
            Name = 'Facility Title',
            Code = 'FAC1',
            CodeSetType = 'Facility Title',
            IsActive = true
        );
        insert facilityCode;

        // Shift
        CodeSet shiftCode = new CodeSet(Name='Day Shift', Code='DAY', CodeSetType='Shift');
        insert shiftCode;

        Shift__c shiftRec = new Shift__c(
            Shift_Name__c = shiftCode.Id,
            Contract__c = contract.Id,
            Shift_Start_Time__c = Time.newInstance(1,0,0,0),
            Shift_End_Time__c = Time.newInstance(9,0,0,0),
            Type__c = 'NP/PA',
            Shift_Iteration__c = '1',
            Shift_Day_of_the_Week__c = 'Monday'
        );
        insert shiftRec;

        
        // ContractPaymentAgreement — inserted FIRST
        ContractPaymentAgreement cpa = new ContractPaymentAgreement(
            Type__c = 'Shift',
            ContractId = contract.Id,
            Name = 'Test CPA',
            AgreementType = 'Preventive Care Agreement'
        );
        insert cpa;

        // PreventiveCareAgreement referencing CPA and Shift
        PreventiveCareAgreement pca = new PreventiveCareAgreement(
            FacilityTitle__c = facilityCode.Id,
            Rate__c = 100,
            ContractPaymentAgreementId = cpa.Id,
            Shift__c = shiftRec.Id,
            BonusMeasureType = 'NA',
            TargetMeasurePercent = 0,
            BonusPayout = 0
        );
        insert pca;
        
        PreventiveCareAgreement pca1 = new PreventiveCareAgreement(
            FacilityTitle__c = facilityCode.Id,
            Rate__c = 101,
            ContractPaymentAgreementId = cpa.Id,
            Shift__c = shiftRec.Id,
            BonusMeasureType = 'NA',
            TargetMeasurePercent = 0,
            BonusPayout = 0
        );
        insert pca1;
    }
    
    @IsTest
    static void testHappyPath_validRate() {
        // Arrange
        Contract testContract = [SELECT Id FROM Contract LIMIT 1];
        CodeSet facility = [SELECT Id FROM CodeSet WHERE CodeSetType='Facility Title' LIMIT 1];
        CodeSet shift = [SELECT Code FROM CodeSet WHERE CodeSetType='Shift' LIMIT 1];

        Map<String, Object> input = new Map<String, Object>{
            'ContextId' => testContract.Id,
            'Rate' => 100,
            'UnitOfMeasure' => 'Per Hour',
            'ListOfFacilityTitleIds' => new List<Object>{
                new Map<String,Object>{'value' => facility.Id}
            },
            'shifts' => new List<Object>{
                new Map<String,Object>{'ShiftCode' => shift.Code}
            }
        };
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> args = new Map<String, Object>{
            'input' => input, 'output' => output, 'options' => new Map<String, Object>()
        };

        // Act
        CheckRatesForServiceAccFacility handler = new CheckRatesForServiceAccFacility();
        handler.call('ValidateRate', args);

        // Assert
        System.assertEquals(true, output.containsKey('rateValidated'));
    }
}