knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>Custom Attachments for Opportunity</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Needs Assessment</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Deal Profile</fullName>
            </value>
            <value>
                <fullName>Fee for Service Proposed # Per Patient</fullName>
            </value>
            <value>
                <fullName>Fee Schedule Analysis</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer Reimbursement Analysis</fullName>
            </value>
            <value>
                <fullName>Pro Forma</fullName>
            </value>
            <value>
                <fullName>Proforma at Contract Signature</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Provider Coverage Worksheet</fullName>
            </value>
            <value>
                <fullName>Provider Pay Rate / Market Analysis</fullName>
            </value>
            <value>
                <fullName>Risk Venue (Facility &amp; County) Analysis</fullName>
            </value>
            <value>
                <fullName>Volume Analysis Worksheet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/OpportunityAttachmentTriggerHandlerTest.cls
/**
 * Created by srinivasseri on 1/19/16.
 */

@IsTest(seeAllData=true)
private class OpportunityAttachmentTriggerHandlerTest {
    static OpportunityAttachmentTriggerHandler handler = new OpportunityAttachmentTriggerHandler();

    static testMethod void testGetHigherVersion() {
        Integer versionNumber = handler.getHigherVersion(1, 'V02');
        System.assertEquals(versionNumber, 2);
    }

    static testMethod void testSetVersion() {
        Opportunity opportunity = OpportunityTestDataHelper.getOpportunity();

        Opportunity_Attachment__c oac = new Opportunity_Attachment__c();
        oac.Opportunity__c = opportunity.Id;
        oac.Version__c = 'V03';
        oac.Document_Type__c  = 'MOU';
        Map<String, Integer> versionsMap = new Map<String, Integer>();

        handler.setVersion(oac, versionsMap);
        System.assertEquals(oac.Version__c, 'V01');

        versionsMap.put('MOU', 3);
        handler.setVersion(oac, versionsMap);
        System.assertEquals(oac.Version__c, 'V04');

        versionsMap.clear();
        versionsMap.put('Proposal', 2);
        handler.setVersion(oac, versionsMap);
        System.assertEquals(oac.Version__c, 'V01');
    }

    static testMethod void testUpdateFinalFlag() {
        Opportunity opportunity = OpportunityTestDataHelper.getOpportunity();

        Opportunity_Attachment__c oac = new Opportunity_Attachment__c();
        oac.Opportunity__c = opportunity.Id;
        oac.Version__c = 'V03';
        oac.Document_Type__c  = 'MOU';

        Opportunity_Attachment__c oa1 = new Opportunity_Attachment__c();
        oa1.Opportunity__c = opportunity.Id;
        oa1.Version__c = '';
        oa1.Document_Type__c  = 'MOU';
        oa1.Final__c = TRUE;
        insert(oa1);

        Opportunity_Attachment__c oa2 = new Opportunity_Attachment__c();
        oa2.Opportunity__c = opportunity.Id;
        oa2.Version__c = '';
        oa2.Document_Type__c  = 'MOU';
        oa2.Final__c = TRUE;
        insert(oa2);

        Opportunity_Attachment__c inserted = [select Version__c, Final__c from Opportunity_Attachment__c where Id =: oa1.Id];
        System.debug('inserted.Version__c: ' + inserted.Version__c);
        System.debug('inserted.Final__c: ' + inserted.Final__c);
        System.assertEquals(inserted.Version__c, 'V01');
        System.assertEquals(inserted.Final__c, FALSE);

        Opportunity_Attachment__c inserted1 = [select Version__c, Final__c from Opportunity_Attachment__c where Id =: oa2.Id];
        System.debug('inserted1.Version__c: ' + inserted1.Version__c);
        System.debug('inserted1.Final__c: ' + inserted1.Final__c);
        System.assertEquals(inserted1.Version__c, 'V02');
        System.assertEquals(inserted1.Final__c, TRUE);

        Opportunity_Attachment__c attachmentProposal = new Opportunity_Attachment__c();
        attachmentProposal.Opportunity__c = opportunity.Id;
        attachmentProposal.Version__c = 'V02';
        attachmentProposal.Document_Type__c  = 'Proposal';
        attachmentProposal.Final__c = TRUE;
        insert(attachmentProposal);

        Opportunity_Attachment__c apAttachment = [select Version__c, Final__c from Opportunity_Attachment__c where Id =: attachmentProposal.Id];
        System.debug('apAttachment.Version__c: ' + apAttachment.Version__c);
        System.debug('apAttachment.Final__c: ' + apAttachment.Final__c);
        System.assertEquals(apAttachment.Version__c, 'V01');
        System.assertEquals(apAttachment.Final__c, TRUE);

    }

}