knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Contract_Active__c.field-meta.xml
<CustomField>
    <fullName>Contract_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Active Do Not Use</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Link to opportunities</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>Custom Attachments for Opportunity</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Needs Assessment</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Deal Profile</fullName>
            </value>
            <value>
                <fullName>Fee for Service Proposed # Per Patient</fullName>
            </value>
            <value>
                <fullName>Fee Schedule Analysis</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer Reimbursement Analysis</fullName>
            </value>
            <value>
                <fullName>Pro Forma</fullName>
            </value>
            <value>
                <fullName>Proforma at Contract Signature</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Provider Coverage Worksheet</fullName>
            </value>
            <value>
                <fullName>Provider Pay Rate / Market Analysis</fullName>
            </value>
            <value>
                <fullName>Risk Venue (Facility &amp; County) Analysis</fullName>
            </value>
            <value>
                <fullName>Volume Analysis Worksheet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/OpportunityAttachmentTriggerHandler.cls
public with sharing class OpportunityAttachmentTriggerHandler {
    private static Set<String> DOCUMENT_TYPES = new Set<String> { 'MOU', 'Pro Forma', 'Proposal' };

    public OpportunityAttachmentTriggerHandler() {
		
	}

	public void updateDocumentTypeVersion(List<Opportunity_Attachment__c> attachments)	{
		Set<Id> allIds = new Set<Id>();
		List<Opportunity_Attachment__c> existingAttachments = new List<Opportunity_Attachment__c>();
		
		for(Opportunity_Attachment__c a : attachments){
			allIds.add(a.Opportunity__c);
		}
        System.debug('allIds: ' + allIds);


		existingAttachments = [	SELECT 
									Id, Opportunity__c, Document_Type__c, Final__c, Version__c
								FROM 
									Opportunity_Attachment__c 
								WHERE 
									Opportunity__c IN : allIds
                                AND
                                    Final__c = TRUE];
        System.debug('existingAttachments: ' + existingAttachments);
        List<Opportunity_Attachment__c> updatedList  = updateFinalFlag(existingAttachments, attachments);
        update(updatedList);

	}

    /**
     * validate the opportunity attachments if the attachment opportunity Contract.Contract_Active__c is TRUE
     * validate if the attached document is marked as final if the document type is either MOU, Pro Forma or Proposal
     */
    @TestVisible private void validateDocumentTypes(Set<Id> oppIds, List<Opportunity_Attachment__c> attachments) {
        List<Contract> oppContracts = [SELECT Id, Contract_Active__c, Opportunity__c FROM Contract WHERE
                                        Opportunity__c IN : oppIds AND Contract_Active__c = TRUE];
        if(oppContracts.size() == 0)    {
            return;
        }

        for(Contract c : oppContracts)  {
            for(Opportunity_Attachment__c oa : attachments) {
                if(c.Opportunity__c == oa.Opportunity__c && DOCUMENT_TYPES.contains(oa.Document_Type__c) && oa.Final__c == FALSE)   {
                    oa.addError('Final Version of ' + oa.Name + ' must be attached.');
                }
            }
        }

    }

    @TestVisible private List<Opportunity_Attachment__c>  updateFinalFlag(List<Opportunity_Attachment__c> existingAttachments, List<Opportunity_Attachment__c> attachments)  {
        List<Opportunity_Attachment__c> updatedList = new List<Opportunity_Attachment__c>();
        Map<String, Integer> versionsMap = new Map<String, Integer>();
        for(Opportunity_Attachment__c newAttachment : attachments)	{
            for(Opportunity_Attachment__c ex : existingAttachments){
                if(newAttachment.Opportunity__c == ex.Opportunity__c && newAttachment.Final__c == true
                        && newAttachment.Document_Type__c == ex.Document_Type__c){
                    ex.Final__c = false;
                    if(versionsMap.get(ex.Document_Type__c) != null)	{
                        versionsMap.put(ex.Document_Type__c, getHigherVersion(versionsMap.get(ex.Document_Type__c), ex.Version__c));
                    } else	{
                        Integer version = Integer.valueOf(ex.Version__c.substringAfter('V'));
                        versionsMap.put(ex.Document_Type__c, version);
                    }
                    updatedList.add(ex);
                }
            }
            setVersion(newAttachment, versionsMap);
            System.debug('after setVersion: ' + newAttachment.Version__c);
            versionsMap.clear();
        }
        System.debug('updatedList: ' + updatedList);
        return updatedList;
    }

    @TestVisible private void setVersion(Opportunity_Attachment__c opportunityAttachment, Map<String, Integer> versionsMap)	{
        System.debug('setVersion: ' + versionsMap);
		if(versionsMap.size() == 0 || versionsMap.get(opportunityAttachment.Document_Type__c) == null)	{
			opportunityAttachment.Version__c = 'V01';
            return;
		}

		Integer exVersion = versionsMap.get(opportunityAttachment.Document_Type__c);
        System.debug('exVersion: ' + exVersion);
		if(exVersion != null)	{
            ++exVersion;
			opportunityAttachment.Version__c =  (exVersion > 9 ? ('V0' + exVersion) : ('V0' + exVersion));
            System.debug('exVersion after: ' + opportunityAttachment.Version__c);
		}

	}

    @TestVisible private Integer getHigherVersion(Integer oldVersionNumber, String newVersion)	{
		Integer newVersionNumber = Integer.valueOf(newVersion.substringAfter('V'));
        System.debug('getHigherVersion: ' + newVersionNumber);
		return newVersionNumber > oldVersionNumber ? newVersionNumber : oldVersionNumber;
	}
}