knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Link to opportunities</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Total Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <inlineHelpText>Patient Collections plus HPSA (If any)</inlineHelpText>
    <label>Patient Collections</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Subsidy__c.field-meta.xml
<CustomField>
    <fullName>Subsidy__c</fullName>
    <inlineHelpText>Ongoing Subsidy plus any Pass Through Start Up Costs.</inlineHelpText>
    <label>Subsidy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Annual Encounters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>Custom Attachments for Opportunity</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Needs Assessment</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Deal Profile</fullName>
            </value>
            <value>
                <fullName>Fee for Service Proposed # Per Patient</fullName>
            </value>
            <value>
                <fullName>Fee Schedule Analysis</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer Reimbursement Analysis</fullName>
            </value>
            <value>
                <fullName>Pro Forma</fullName>
            </value>
            <value>
                <fullName>Proforma at Contract Signature</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Provider Coverage Worksheet</fullName>
            </value>
            <value>
                <fullName>Provider Pay Rate / Market Analysis</fullName>
            </value>
            <value>
                <fullName>Risk Venue (Facility &amp; County) Analysis</fullName>
            </value>
            <value>
                <fullName>Volume Analysis Worksheet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/OpportunityAttachmentController.cls
public class OpportunityAttachmentController {

    public String version {get;set;}
    public String selectedType {get;set;}
    public List<SelectOption> documentTypeList;
    public Boolean finalVersion {get;set;}
    public String description {get;set;}
    private Opportunity opportunity {get;set;}
    public String fileName {get;set;}
    public Transient Blob fileBody {get;set;}
    public boolean displayPopup {get; set;} 
    public List<Opportunity> Opps {get; set;}
    public Decimal sub {get; set;}

    public  OpportunityAttachmentController(ApexPages.StandardController controller) {
        this.opportunity = (Opportunity)controller.getRecord();
    }

    public void closePopup() {        
        displayPopup = false;    
    }     
    public PageReference showPopup() { 
        try{

            // List<opportunity> Opps = new List<opportunity>();
            // if(opportunity != null){
            //     system.debug('b');
            //     Opps = [SELECT Id, stageName, Subsidy__c, Revenue__c, Volume__c, Margin__c FROM opportunity WHERE Id = :opportunity.id limit 1];
            //   system.debug('c');
            // }
            //  if(fileBody != null && (selectedType == 'Proposal' || selectedType == 'MOU' || selectedType == 'Contract' || selectedType == 'Proforma at Contract Signature')){
            //      system.debug('d');
            //      displayPopup = true;
            //      system.debug('after popup');
            //      return null;
            // } else {
            // }
                if(fileBody == null){
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                        'Could not save attachment. No File attached'));
                    return null;
                } else{
                    processUpload();
                    return new PageReference('/'+opportunity.Id);
                }
                
                   
             
        }
        catch(Exception e) {
            ApexPages.AddMessages(e);
            return null;
        }  
    }

    // creates a new Opportunity_Attachment__c record
    private Database.SaveResult saveCustomAttachment() {
        Opportunity_Attachment__c obj = new Opportunity_Attachment__c();
        obj.opportunity__c = opportunity.Id;
        obj.description__c = description;
        obj.version__c = 'V01';
        obj.final__c = finalVersion;
        obj.document_Type__c = selectedType;
        // fill out custom obj fields
        return Database.insert(obj);
    }

    // create an actual Attachment record with the Opportunity_Attachment__c as parent
    private Database.SaveResult saveStandardAttachment(Id parentId) {
        Database.SaveResult result;

        Attachment attachment = new Attachment();
        attachment.body = this.fileBody;
        attachment.name = this.fileName;
        attachment.parentId = parentId;
        // insert the attahcment
        result = Database.insert(attachment);
        // reset the file for the view state
        fileBody = Blob.valueOf(' ');
        return result;
    }

    /**
    * Upload process is:
    *  1. Insert new Opportunity_Attachment__c record
    *  2. Insert new Attachment with the new Opportunity_Attachment__c record as parent
    *  3. Update the Opportunity_Attachment__c record with the ID of the new Attachment
    **/
    public PageReference processUpload() {
        
        try {
            
            Database.SaveResult customAttachmentResult = saveCustomAttachment();
            System.debug('processUpload: ' + opportunity.Id);

            if (customAttachmentResult == null || !customAttachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                        'Could not save attachment.'));
                return null;
            }

            Database.SaveResult attachmentResult = saveStandardAttachment(customAttachmentResult.getId());

            if (attachmentResult == null || !attachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                        'Could not save attachment.'));
                return null;
            } else {
                // update the custom attachment record with some attachment info
                Opportunity_Attachment__c customAttachment = [select id from Opportunity_Attachment__c where id = :customAttachmentResult.getId()];
                customAttachment.name = this.fileName;
                customAttachment.Attachment__c = attachmentResult.getId();
                update customAttachment;
            }

        } catch (Exception e) {
            ApexPages.AddMessages(e);
            return null;
        }

        return new PageReference('/'+opportunity.Id);
    }

    public PageReference back() {
        return new PageReference('/'+opportunity.Id);
    }

    public List<SelectOption> getDocumentTypeList() {
        documentTypeList = new List<SelectOption>();
        Schema.DescribeFieldResult metadata = Opportunity_Attachment__c.Document_Type__c.getDescribe();
        List<Schema.PickListEntry> metadataPickList = metadata.getPickListValues();
        documentTypeList.add(new SelectOption('','None'));
        for(Schema.PickListEntry obj: metadataPickList){
            documentTypeList.add(new SelectOption(obj.getLabel(),obj.getValue()));
        }
        return documentTypeList;
    }

}