knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Link to opportunities</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Contract/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Practice Operations</label>
</RecordType>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Lead/fields/Service_s__c.field-meta.xml
<CustomField>
    <fullName>Service_s__c</fullName>
    <label>Service(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>WW</fullName>
            </value>
            <value>
                <fullName>TM</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <inlineHelpText>Place the date of the first service start date here.  Each service should have its associated start dates listed on the Service record.</inlineHelpText>
    <label>1st Service Start Date</label>
    <type>Date</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Contract_Customer_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Customer_Signed_Date__c</fullName>
    <description>Contract Customer Signed Date</description>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Created_from_Lead__c.field-meta.xml
<CustomField>
    <fullName>Created_from_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is mapped from Leads.</description>
    <label>Created from Lead</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Expected_Sign_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Sign_Date__c</fullName>
    <description>Expected Sign Date</description>
    <label>Expected Sign Date</label>
    <type>Date</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/MOU_Sign_Date__c.field-meta.xml
<CustomField>
    <fullName>MOU_Sign_Date__c</fullName>
    <label>MOU Sign Date</label>
    <type>Date</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>Custom Attachments for Opportunity</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Needs Assessment</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Deal Profile</fullName>
            </value>
            <value>
                <fullName>Fee for Service Proposed # Per Patient</fullName>
            </value>
            <value>
                <fullName>Fee Schedule Analysis</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer Reimbursement Analysis</fullName>
            </value>
            <value>
                <fullName>Pro Forma</fullName>
            </value>
            <value>
                <fullName>Proforma at Contract Signature</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Provider Coverage Worksheet</fullName>
            </value>
            <value>
                <fullName>Provider Pay Rate / Market Analysis</fullName>
            </value>
            <value>
                <fullName>Risk Venue (Facility &amp; County) Analysis</fullName>
            </value>
            <value>
                <fullName>Volume Analysis Worksheet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity_Attachment__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
/**
 * Created by srinivasseri on 1/20/16.
 */

@IsTest(seeAllData=true)
private class OpportunityTriggerHandlerTest {
    static OpportunityTriggerHandler opportunityTriggerHandler = new OpportunityTriggerHandler();

   static testMethod void itShouldCopyOpptyAttachmentsToAccount() {
        Test.startTest();

        Opportunity opportunity = getOpportunity('Marketing Qualified Lead');

        insertOpportunityAttachment(opportunity, TRUE, 'MOU');
        insertOpportunityAttachment(opportunity, FALSE, 'MOU');

        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);

        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 2);

        Test.stopTest();
    }

    static testMethod void itShouldNotCopyOpptyAttachmentsToAccount() {
        Test.startTest();

        Opportunity opportunity = getOpportunity('Marketing Qualified Lead');

        insertOpportunityAttachment(opportunity, FALSE, 'MOU');

        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);

        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 1);

        Test.stopTest();
    }

    
    static testMethod void testMarketingQualifiedLead_Stage() {
        Test.startTest();

        Opportunity opportunity = getOpportunity('Marketing Qualified Lead');

        Test.stopTest();
    }
    
    static testMethod void testSalesQualifiedOpportunity_Stage() {
        Test.startTest();

        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');
        
        Test.stopTest();
    }
    
    static testMethod void testProposalRequest_Stage() {
        
        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');
        insertOpportunityAttachment(opportunity, FALSE, 'Movie Plan Worksheet');

        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);

        Test.startTest();

        opportunity.StageName='Proposal Request';

        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 1);

        Test.stopTest();
    }

    static testMethod void testProposalDevelopment_Stage() {
        
        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');

        insertOpportunityAttachment(opportunity, FALSE, 'Client Needs Assessment');
        insertOpportunityAttachment(opportunity, FALSE, 'Movie Plan Worksheet');
        
        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);
        
        Test.startTest();

        opportunity.StageName='Proposal Development';

        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 2);

        Test.stopTest();
    }
    
    static testMethod void testProposalPresented_Stage() {
        
        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');

        insertOpportunityAttachment(opportunity, TRUE, 'Pro Forma');
        insertOpportunityAttachment(opportunity, TRUE, 'Proposal');
        insertOpportunityAttachment(opportunity, FALSE, 'Client Needs Assessment');
        insertOpportunityAttachment(opportunity, FALSE, 'Movie Plan Worksheet');
        
        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);
        
        Test.startTest();
        
        opportunity.StageName='Proposal Presented';

        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 4);

        Test.stopTest();
    }
    
    static testMethod void testDownSelect_Stage() {
        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');

        insertOpportunityAttachment(opportunity, FALSE, 'Movie Plan Worksheet');
        insertOpportunityAttachment(opportunity, FALSE, 'Client Needs Assessment');
        insertOpportunityAttachment(opportunity, TRUE, 'Proposal');
        insertOpportunityAttachment(opportunity, TRUE, 'Pro Forma');

        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);
        
        Test.startTest();
        
        opportunity.StageName='Down Select';

        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 4);

        Test.stopTest();
    }
    
        
    static testMethod void testVerbalAward_Stage() {
        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');

        insertOpportunityAttachment(opportunity, FALSE, 'Movie Plan Worksheet');
        insertOpportunityAttachment(opportunity, FALSE, 'Client Needs Assessment');
        insertOpportunityAttachment(opportunity, TRUE, 'Proposal');
        insertOpportunityAttachment(opportunity, TRUE, 'Pro Forma');

        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);
        
        Test.startTest();
        
        Opportunity.StageName='Verbal Award';

        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 4);

        Test.stopTest();
    }
    
    static testMethod void testMOUSigned_Stage() {
        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');

        insertOpportunityAttachment(opportunity, FALSE, 'Movie Plan Worksheet');
        insertOpportunityAttachment(opportunity, FALSE, 'Client Needs Assessment');
        insertOpportunityAttachment(opportunity, TRUE, 'Proposal');
        insertOpportunityAttachment(opportunity, TRUE, 'Pro Forma');
        insertOpportunityAttachment(opportunity, TRUE, 'MOU');

        opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);
        
        Test.startTest();
        
        Opportunity.StageName='MOU Signed';
        
        List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        System.assertEquals(accountAttachments.size(), 5);

        Test.stopTest();
    }
    
    static testMethod void testContractSigned_Stage() {
        Opportunity opportunity = getOpportunity('Sales Qualified Opportunity');
        
        insertOpportunityAttachment(opportunity, FALSE, 'Movie Plan Worksheet');
        insertOpportunityAttachment(opportunity, FALSE, 'Client Needs Assessment');
        insertOpportunityAttachment(opportunity, TRUE, 'Proposal');
        insertOpportunityAttachment(opportunity, TRUE, 'Pro Forma');
        insertOpportunityAttachment(opportunity, TRUE, 'MOU');
        insertOpportunityAttachment(opportunity, TRUE, 'Contract');
         insertOpportunityAttachment(opportunity, TRUE, 'Proforma at Contract Signature');

        //opportunityTriggerHandler.attachOpportunityAttachmentsToAccount(opportunity);
        
        Test.startTest();


        
        Opportunity.StageName='Contract Signed';
        Opportunity.MOU_Sign_Date__c = System.today();
        Opportunity.Expected_Sign_Date__c = System.today();
        Opportunity.Contract_Customer_Signed_Date__c = System.today();
        Opportunity.Actual_Start_Date__c = System.today();
        
        update Opportunity;
        
    
        //List<Attachment> accountAttachments = [SELECT Id, Body, Name FROM Attachment WHERE ParentId =: opportunity.AccountId];
        //System.assertEquals(accountAttachments.size(), 6);

        Test.stopTest();
    }
    

    
    /*static testMethod void testValidateDocumentTypesSuccess() {
        Test.startTest();

        Opportunity opportunity = getOpportunity();
        insertOpportunityAttachment(opportunity, TRUE, 'MOU');
        insertOpportunityAttachment(opportunity, TRUE, 'Pro Forma');
        insertOpportunityAttachment(opportunity, TRUE, 'Proposal');

        opportunity.StageName='Started';
        update(opportunity);

        Test.stopTest();
    }
    static testMethod void testValidateDocumentTypesSemiSuccess() {
        Test.startTest();

        Opportunity opportunity = getOpportunity();
        insertOpportunityAttachment(opportunity, TRUE, 'MOU');
        insertOpportunityAttachment(opportunity, TRUE, 'Pro Forma');
        insertOpportunityAttachment(opportunity, TRUE, 'Proposal');

        opportunity.StageName='Started';
        try{
            update(opportunity);
        } catch (DmlException dml)  {
            System.debug('dml ex: '+ dml.getMessage());
            System.assert(dml.getMessage().contains('Final Version of'));
        }

        Test.stopTest();
    }*/


    private static Id getRecordTypeId()    {
        RecordType rtOpp = [Select Name, DeveloperName From RecordType
        Where SObjectType = 'Opportunity' and Name = 'HM Sales Opportunity'];
        return rtOpp.Id;
    }

    private static Opportunity getOpportunity(String stage)   {
        Account acc1 = new Account(Name='Opportunity Account');
        insert acc1;

        Opportunity opportunity = new Opportunity (
                Name = 'Opp-Test',
                CloseDate = Date.today(),
                //StageName = 'Marketing Qualified Lead',
                StageName = stage,
                Created_from_Lead__c = true,
                //Service_s__c  = 'HM;WW',
                AccountId = acc1.Id,
                RecordTypeId = getRecordTypeId()
        );
        insert opportunity;
        System.debug('Opportunity: ' + opportunity);
        return opportunity;
    }

    private static void insertOpportunityAttachment(Opportunity opportunity, Boolean finalFlag, String documentType)  {
        Attachment attachment = new Attachment();
        attachment.parentId = opportunity.Id;
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body' + opportunity.Id + finalFlag);
        attachment.body = bodyBlob;
        attachment.name = 'test attachment';
        System.debug('attachment: ' + attachment);
        insert(attachment);

        Opportunity_Attachment__c obj = new Opportunity_Attachment__c();
        obj.opportunity__c = opportunity.Id;
        obj.description__c = 'test';
        obj.version__c = 'V01';
        obj.final__c = finalFlag;
        obj.document_Type__c = documentType;
        obj.name = attachment.name;
        obj.Attachment__c = attachment.Id;
        insert(obj);
    }
    
}