knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Lead/fields/Service_s__c.field-meta.xml
<CustomField>
    <fullName>Service_s__c</fullName>
    <label>Service(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>WW</fullName>
            </value>
            <value>
                <fullName>TM</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Opportunity/fields/Created_from_Lead__c.field-meta.xml
<CustomField>
    <fullName>Created_from_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is mapped from Leads.</description>
    <label>Created from Lead</label>
    <type>Checkbox</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/OpportunityTestDataHelper.cls
/**
 * Created by srinivasseri on 2/8/16.
 */

public with sharing class OpportunityTestDataHelper {

    public static Opportunity getOpportunity()   {
        Account acc1 = new Account(Name='Opportunity Account');
        insert acc1;

        Opportunity opportunity = new Opportunity (
                Name = 'Opp-Test',
                CloseDate = Date.today(),
                StageName = 'Marketing Qualified Lead',
                Created_from_Lead__c = true,
                //Service_s__c  = 'HM;WW',
                AccountId = acc1.Id,
                RecordTypeId = getRecordTypeId()
        );
        insert opportunity;
        System.debug('Opportunity: ' + opportunity);
        return opportunity;
    }

    public static Id getRecordTypeId()    {
        RecordType rtOpp = [Select Name, DeveloperName From RecordType
        Where SObjectType = 'Opportunity' and Name = 'HM Sales Opportunity'];
        return rtOpp.Id;
    }


}