knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/ContractPaymentAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stipend</fullName>
            </value>
            <value>
                <fullName>Shift</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Locum</fullName>
            </value>
            <value>
                <fullName>Leadership Incentives</fullName>
            </value>
            <value>
                <fullName>Locums</fullName>
                <isActive>false</isActive>
                <label>Locums</label>
            </value>
            <value>
                <fullName>Locums On Call</fullName>
                <isActive>false</isActive>
                <label>Locums On Call</label>
            </value>
            <value>
                <fullName>Locums Travel</fullName>
                <isActive>false</isActive>
                <label>Locums Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/FacilityTitle__c.field-meta.xml
<CustomField>
    <fullName>FacilityTitle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Title</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>CodeSet.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CodeSet.CodeSetType</field>
            <operation>equals</operation>
            <value>Facility Title</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Preventive Care Agreements (Facility Title)</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements1</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Shift__c.field-meta.xml
<CustomField>
    <fullName>Shift__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shift</label>
    <referenceTo>Shift__c</referenceTo>
    <relationshipLabel>Preventive Care Agreements</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/PreventiveCareAgreement/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Preventive Care Agreements (Type)</relationshipLabel>
    <relationshipName>Preventive_Care_Agreements2</relationshipName>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/Shift__c.object-meta.xml
<CustomObject>
    <label>Shift</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Shift Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Shift_Name__c.field-meta.xml
<CustomField>
    <fullName>Shift_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shift Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CodeSet.CodeSetType</field>
            <operation>equals</operation>
            <value>Shift</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/objects/Shift__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NP/PA</fullName>
            </value>
            <value>
                <fullName>MD/DO</fullName>
            </value>
            <value>
                <fullName>RN/LPN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

knowledge/metadata/sf-pp-main-qa/sf-pp-main-qa/force-app/main/default/classes/CheckRatesForServiceAccFacility.cls
global class CheckRatesForServiceAccFacility implements Callable {
	 public Object call(String action, Map<String, Object> args) {
        Map<String, Object> input = (Map<String, Object>) args.get('input');
        Map<String, Object> output = (Map<String, Object>) args.get('output');
        Map<String, Object> options = (Map<String, Object>) args.get('options');
        return invokeMethod(action, input, output, options);
    }
    
    global Boolean invokeMethod(String methodName, Map<String, Object> inputs,
        Map<String, Object> output, Map<String, Object> options) {
        if(methodName == 'ValidateRate') {
            output.put('rateValidated', validateRate(inputs));
        }
        return true;
    }
    
     public Boolean validateRate(Map<String,Object> input) {
        
        //Output Value
        Boolean Validated = false;
        //Input Value
        String contractId = String.valueOf(input.get('ContextId'));
        Decimal rate = Decimal.valueOf(String.valueOf(input.get('Rate')));
        String unitOfMeasure = String.valueOf(input.get('UnitOfMeasure'));
        
        List<String> facilityTitleIds = new List<String>();
		Object rawFacilityObj = input.get('ListOfFacilityTitleIds');

        if (rawFacilityObj instanceof List<Object>) {
            for (Object obj : (List<Object>) rawFacilityObj) {
                if (obj instanceof Map<String, Object>) {
                    facilityTitleIds.add(String.valueOf(((Map<String, Object>) obj).get('value')));
                }
            }
        }
        
        Set<String> shiftCodes = new Set<String>();
        Object rawShiftObj = input.get('shifts');
        if (rawShiftObj instanceof List<Object>) {
            for (Object obj : (List<Object>) rawShiftObj) {
                if (obj instanceof Map<String, Object>) {
                    shiftCodes.add(String.valueOf(((Map<String, Object>) obj).get('ShiftCode')));
                }
            }
        }
   		AggregateResult[] aggResult;
   		if (!facilityTitleIds.isEmpty() && !shiftCodes.isEmpty()) {
			try {
                aggResult = [
                    SELECT MAX(Rate__c) maxRate,
                           MIN(Rate__c) minRate,
                    	   FacilityTitle__c,
                    	   Shift__r.Shift_Name__r.Code
                    FROM PreventiveCareAgreement
                    WHERE FacilityTitle__c IN :facilityTitleIds
                    AND Shift__r.Shift_Name__r.Code IN :shiftcodes
                    AND ContractPaymentAgreement.Type__c = 'Shift'
                    AND ContractPaymentAgreement.ContractId = :contractId
                    GROUP BY FacilityTitle__c,Shift__r.Shift_Name__r.Code
                ];
            } catch (QueryException qe) {
                return false;
            }
        
    	}
        Integer expectedCombinations = facilityTitleIds.size() * shiftcodes.size();
         // Check if every combination has a record
    	if (aggResult.size() != expectedCombinations) {
            return false;
   		}
         
        for (AggregateResult ar : aggResult) {
            Decimal maxRate = (Decimal) ar.get('maxRate');
            Decimal minRate = (Decimal) ar.get('minRate');
            // If entered rate doesn’t match the existing range for any combination
            if (maxRate != minRate || maxRate != rate) {
                validated = false;
                break;
            } else {
                validated = true;
            }
        }
         return validated;
     }   
}